CREATE DATABASE `DB_RISK` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `DB_RISK`;

DROP TABLE IF EXISTS `TB_ADON_FLOW_PLCY`;
CREATE TABLE `TB_ADON_FLOW_PLCY` (
  `SAFPLCY_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SAFPLCY_ID`)
);

DROP TABLE IF EXISTS `TB_ALLW_GEO_LOCA`;
CREATE TABLE `TB_ALLW_GEO_LOCA` (
  `IAGLOCA_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SCTRY_CD` varchar(255) NOT NULL,
  `SCHCK_PRVC_YN` varchar(255) NOT NULL,
  `SPRVC_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IAGLOCA_NO`)
);

DROP TABLE IF EXISTS `TB_ALLW_NTWK_CIDR`;
CREATE TABLE `TB_ALLW_NTWK_CIDR` (
  `IANCIDR_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SNTWK_CIDR` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IANCIDR_NO`)
);

DROP TABLE IF EXISTS `TB_ALLW_WIFI_ROUT`;
CREATE TABLE `TB_ALLW_WIFI_ROUT` (
  `IAWROUT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SWIFI_ROUT_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IAWROUT_NO`)
);

DROP TABLE IF EXISTS `TB_API_SRVC_LOG`;
CREATE TABLE `TB_API_SRVC_LOG` (
  `IASLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SSRVC_CD` varchar(255) NOT NULL,
  `SSRVC_TYPE_CD` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SIP_ARR` varchar(255) NOT NULL,
  `SMSG` varchar(1000) NOT NULL,
  `SSTART_DT` varchar(255) NOT NULL,
  `SEND_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IASLOG_NO`)
);

DROP TABLE IF EXISTS `TB_APP_FLOW_PLCY`;
CREATE TABLE `TB_APP_FLOW_PLCY` (
  `SAFPLCY_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SFLOW_CD` varchar(255) NOT NULL,
  `SCORE_INFR_PRVS_SPEC_ID` varchar(255) NOT NULL,
  `SCRET_DATA_FLOW_ON_AUTH_YN` varchar(255) NOT NULL,
  `SDATA_FLOW_MFA_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SAFPLCY_ID`),
  KEY `IDX_APP_FLOW_PLCY_001` (`SCLUD_ID`,`SFLOW_PLCY_MSTR_ID`),
  KEY `IDX_APP_FLOW_PLCY_002` (`SCLUD_ID`,`SAFPLCY_ID`)
);

DROP TABLE IF EXISTS `TB_APP_FLOW_PLCY_ALIS`;
CREATE TABLE `TB_APP_FLOW_PLCY_ALIS` (
  `SAFPALIS_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SAPP_FLOW_PLCY_ID` varchar(255) NOT NULL,
  `SAPP_CD` varchar(255) NOT NULL,
  `SAPP_MSTR_ID` varchar(255) NOT NULL,
  `SALIS_NM` varchar(255) NOT NULL,
  `SALIS_URL` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SAFPALIS_ID`),
  KEY `IDX_APP_FLOW_PLCY_ALIS_001` (`SCLUD_ID`,`SFLOW_PLCY_MSTR_ID`,`SAPP_MSTR_ID`),
  KEY `IDX_APP_FLOW_PLCY_ALIS_002` (`SCLUD_ID`,`SAPP_FLOW_PLCY_ID`,`SAPP_MSTR_ID`)
);

DROP TABLE IF EXISTS `TB_APP_FLOW_RJCT_LOG`;
CREATE TABLE `TB_APP_FLOW_RJCT_LOG` (
  `SAFRLOG_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_ID` varchar(255) NOT NULL,
  `SDEST_URL` varchar(255) NOT NULL,
  `SDEST_TRSP_PRTC_CD` varchar(255) NOT NULL,
  `SDEST_IP` varchar(255) NOT NULL,
  `IDEST_PORT` bigint(20) NOT NULL,
  `IRJCT_CNT` bigint(20) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SAFRLOG_ID`)
);

DROP TABLE IF EXISTS `TB_APP_FLOW_RJCT_ROUT_LOG`;
CREATE TABLE `TB_APP_FLOW_RJCT_ROUT_LOG` (
  `IAFRRLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SAPP_FLOW_RJCT_LOG_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SROUT_PLCY_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IAFRRLOG_NO`)
);

DROP TABLE IF EXISTS `TB_APP_FLOW_RJCT_USER_LOG`;
CREATE TABLE `TB_APP_FLOW_RJCT_USER_LOG` (
  `IAFRULOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SAPP_FLOW_RJCT_LOG_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IAFRULOG_NO`)
);

DROP TABLE IF EXISTS `TB_APP_MSTR`;
CREATE TABLE `TB_APP_MSTR` (
  `SAMSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SAMSTR_ID`),
  KEY `IDX_APP_MSTR_001` (`SPLTF_CD`)
);

DROP TABLE IF EXISTS `TB_AWNS_NOTI`;
CREATE TABLE `TB_AWNS_NOTI` (
  `SANOTI_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SNOTI_NM` varchar(255) NOT NULL,
  `SNOTI_SMS_YN` varchar(255) NOT NULL,
  `SNOTI_EMAL_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SANOTI_ID`)
);

DROP TABLE IF EXISTS `TB_AWNS_NOTI_ITEM`;
CREATE TABLE `TB_AWNS_NOTI_ITEM` (
  `IANITEM_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SAWNS_NOTI_ID` varchar(255) NOT NULL,
  `SNOTI_ITEM_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IANITEM_NO`)
);

DROP TABLE IF EXISTS `TB_AWNS_NOTI_LOG`;
CREATE TABLE `TB_AWNS_NOTI_LOG` (
  `IANLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `STYPE_CD` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SFROM` varchar(255) NOT NULL,
  `STO` varchar(255) NOT NULL,
  `SNOTI_TITLE` varchar(255) NOT NULL,
  `SNOTI_INFO` longtext NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SSEND_TYPE_CD` varchar(255) NOT NULL DEFAULT '',
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IANLOG_NO`),
  KEY `IDX_AWNS_NOTI_LOG_01` (`SSTAT_CD`)
);

DROP TABLE IF EXISTS `TB_AWNS_NOTI_USER`;
CREATE TABLE `TB_AWNS_NOTI_USER` (
  `IANUSER_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SAWNS_NOTI_ID` varchar(255) NOT NULL,
  `SCORE_USER_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IANUSER_NO`)
);

DROP TABLE IF EXISTS `TB_AWNS_VRTL_GW_MSG`;
CREATE TABLE `TB_AWNS_VRTL_GW_MSG` (
  `SAVGMSG_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCTRL_FLOW_EXCP_CATE_CD` varchar(255) NOT NULL,
  `SMSG_LV_CD` varchar(255) NOT NULL,
  `SMSG` varchar(500) NOT NULL,
  `SHELP_URL` varchar(255) NOT NULL,
  `SHELP_CNTC_INFO` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SAVGMSG_ID`)
);

DROP TABLE IF EXISTS `TB_BHVR_CTRL`;
CREATE TABLE `TB_BHVR_CTRL` (
  `SBCTRL_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SBCTRL_ID`)
);

DROP TABLE IF EXISTS `TB_BKUP_RSTR`;
CREATE TABLE `TB_BKUP_RSTR` (
  `IBRSTR_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `SDESC` varchar(1000) NOT NULL,
  `SBKUP_TEXT` longtext NOT NULL,
  `SRSTR_TEXT` longtext NOT NULL,
  `SCORE_USER_ID` varchar(255) NOT NULL,
  `SCORE_USER_IP` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IBRSTR_NO`)
);

DROP TABLE IF EXISTS `TB_CLCT_EXEC_APP`;
CREATE TABLE `TB_CLCT_EXEC_APP` (
  `ICEAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SLOCA` varchar(4000) NOT NULL,
  `SCODE_SIGN_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICEAPP_NO`)
);

DROP TABLE IF EXISTS `TB_CLCT_INST_APP`;
CREATE TABLE `TB_CLCT_INST_APP` (
  `ICIAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SLOCA` varchar(4000) NOT NULL,
  `SPBLS_NM` varchar(255) NOT NULL,
  `SUNST_CMD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICIAPP_NO`)
);

DROP TABLE IF EXISTS `TB_CLCT_NTWK_LSTN_PORT`;
CREATE TABLE `TB_CLCT_NTWK_LSTN_PORT` (
  `ICNLPORT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `STRSP_PRTC_CD` varchar(255) NOT NULL,
  `SPROC_NM` varchar(255) NOT NULL,
  `IPORT` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICNLPORT_NO`)
);

DROP TABLE IF EXISTS `TB_CLCT_PLTF_PTCH`;
CREATE TABLE `TB_CLCT_PLTF_PTCH` (
  `ICPPTCH_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPLTF_VRSN` varchar(255) NOT NULL,
  `SPTCH_ID` varchar(255) NOT NULL,
  `SPTCH_NM` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICPPTCH_NO`)
);

DROP TABLE IF EXISTS `TB_CLUD`;
CREATE TABLE `TB_CLUD` (
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_SRCH_ID` varchar(255) NOT NULL,
  `SCLUD_NM` varchar(255) NOT NULL,
  `SSRVC_NM` varchar(255) NOT NULL,
  `SMNGR_INFO` mediumtext NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SSLUD_USER_PW_SET_METH_CD` varchar(255) NOT NULL,
  `SINIT_PW` varchar(255) NOT NULL,
  `SINIT_PW_SALT` varchar(255) NOT NULL,
  `SPW_PLCY_CD_ARR` varchar(255) NOT NULL,
  `SDEL_YN` varchar(255) NOT NULL DEFAULT 'N',
  `SRGST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCLUD_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_ALLW_MENU`;
CREATE TABLE `TB_CLUD_ALLW_MENU` (
  `ICAMENU_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SMENU_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ICAMENU_NO`)
);

DROP TABLE IF EXISTS `TB_CLUD_APRV`;
CREATE TABLE `TB_CLUD_APRV` (
  `SCAPRV_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SAPRV_TRGT_CD` varchar(255) NOT NULL,
  `SAPRV_TRGT_ID` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SDEVC_PLTF_CD` varchar(255) NOT NULL,
  `SDEVC_MODL_NM` varchar(255) NOT NULL,
  `SUSE_STRT_DT` varchar(255) NOT NULL DEFAULT '',
  `SUSE_END_DT` varchar(255) NOT NULL DEFAULT '',
  `SDEVC_USAG_TYPE` varchar(255) NOT NULL,
  `SRQST_DT` varchar(255) NOT NULL,
  `SRJCT_DT` varchar(255) NOT NULL,
  `SAPRV_DT` varchar(255) NOT NULL DEFAULT '',
  `SRQST_RESN` text NOT NULL,
  `SRJCT_RESN` text NOT NULL,
  `SNTWK_ADDR` varchar(255) NOT NULL DEFAULT '',
  `SAPRV_STAT_CD` varchar(255) NOT NULL,
  PRIMARY KEY (`SCAPRV_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_APRV_TEMP`;
CREATE TABLE `TB_CLUD_APRV_TEMP` (
  `SCATEMP_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCATEMP_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_ID_AUTH`;
CREATE TABLE `TB_CLUD_ID_AUTH` (
  `ICIAUTH_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `STRGT_ID` varchar(255) NOT NULL,
  `SAUTH_ID` varchar(255) NOT NULL,
  `SOTP` varchar(255) NOT NULL,
  `IRETR_CNT` bigint(20) NOT NULL,
  `SRQST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICIAUTH_NO`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER`;
CREATE TABLE `TB_CLUD_USER` (
  `SCUSER_ID` varchar(255) NOT NULL,
  `SUSER_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SUSE_STRT_DT` varchar(255) NOT NULL,
  `SUSE_END_DT` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SRSTR_RESN` varchar(255) NOT NULL,
  `SPREV_STAT_CD` varchar(255) NOT NULL DEFAULT '',
  `SRGST_APRV_ID` varchar(255) NOT NULL,
  `SRGST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUSER_ID`),
  KEY `IDX_CLUD_USER_001` (SUSER_MSTR_ID, SCLUD_ID)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_CHNG_HIST`;
CREATE TABLE `TB_CLUD_USER_CHNG_HIST` (
  `ICUCHIST_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SUSER_MSTR_ID` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SCHNG_TYPE_CD` varchar(255) NOT NULL,
  `SSYNC_STAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICUCHIST_NO`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_DEVC`;
CREATE TABLE `TB_CLUD_USER_DEVC` (
  `SCUDEVC_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPLTF_VRSN` varchar(255) NOT NULL,
  `SHOST_NM` varchar(255) NOT NULL,
  `SMODL_NM` varchar(255) NOT NULL,
  `SDEVC_PRDT_NM` varchar(255) NOT NULL DEFAULT '',
  `SDEVC_REAL_ID` varchar(255) NOT NULL,
  `SDEVC_SGNT` varchar(255) NOT NULL,
  `SDEVC_USER_NM` varchar(255) NOT NULL,
  `SDEVC_USAG_TYPE` varchar(255) NOT NULL,
  `SVRTL_GW_CD` varchar(255) NOT NULL,
  `SVRTL_GW_VRSN` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SRSTR_RESN` varchar(500) NOT NULL,
  `SUSE_STRT_DT` varchar(255) NOT NULL,
  `SUSE_END_DT` varchar(255) NOT NULL,
  `ITEMP_APRV_STRT_TS` bigint(20) NOT NULL,
  `ITEMP_APRV_EXPR_TS` bigint(20) NOT NULL,
  `SRGST_APRV_ID` varchar(255) NOT NULL,
  `SUSE_AUTO_LOGN_YN` varchar(255) NOT NULL,
  `SFRST_EXEC_PATH` varchar(255) NOT NULL,
  `SITGR_STAT_CD` varchar(255) NOT NULL,
  `SPRRT_VPN_CD` varchar(255) NOT NULL DEFAULT '',
  `SUPDT_CI_YN` varchar(255) NOT NULL DEFAULT '',
  `SCNCT_DT` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUDEVC_ID`),
  KEY `IDX_CLUD_USER_DEVC_001` (`SDEVC_REAL_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_DEVC_NTWK`;
CREATE TABLE `TB_CLUD_USER_DEVC_NTWK` (
  `SCUDNTWK_ID` varchar(255) NOT NULL,
  `SCLUD_USER_DEVC_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `SWIFI_ROUT_ID` varchar(255) NOT NULL,
  `SSRC_IP` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SRSTR_RESN` varchar(500) NOT NULL,
  `SRGST_APRV_ID` varchar(255) NOT NULL,
  `SCNCT_DT` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUDNTWK_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_NODE`;
CREATE TABLE `TB_CLUD_USER_NODE` (
    `SCUNODE_ID` varchar(255) NOT NULL,
    `SCLUD_ID` varchar(255) NOT NULL,
    `SCLUD_USER_ID` varchar(255) NOT NULL,
    `SLOGN_ID` varchar(255) NOT NULL,
    `SPLTF_CD` varchar(255) NOT NULL,
    `SHOST_NM` varchar(255) NOT NULL,
    `SMODL_NM` varchar(255) NOT NULL,
    `SDEVC_USER_NM` varchar(255) NOT NULL,
    `SPRRT_VPN_CD` varchar(255) NOT NULL DEFAULT '',
    `SIPSEC_VPN_STTC_IP` varchar(255) NOT NULL,
    `SSSL_VPN_STTC_IP` varchar(255) NOT NULL,
    `SINST_DT` varchar(255) NOT NULL,
    `SUPDT_DT` varchar(255) NOT NULL,
    PRIMARY KEY (`SCUNODE_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_FAVR`;
CREATE TABLE `TB_CLUD_USER_FAVR` (
  `ICUFAVR_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SAPP_FLOW_PLCY_ALIS_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICUFAVR_NO`),
  KEY `IDX_CLUD_USER_FAVR_001` (SCLUD_ID, SCLUD_USER_ID)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_GRUP`;
CREATE TABLE `TB_CLUD_USER_GRUP` (
  `SCUGRUP_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SREF_USER_GRUP_ID` varchar(255) NOT NULL,
  `SGRUP_NM` varchar(255) NOT NULL,
  `SGRUP_FULL_NM` varchar(255) NOT NULL,
  `IGRUP_LV` bigint(20) NOT NULL,
  `ISORT` bigint(20) NOT NULL,
  `SRSTR_RESN` varchar(500) NOT NULL,
  `SUSE_STRT_DT` varchar(255) NOT NULL,
  `SUSE_END_DT` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SSYNC_USER_GRUP_ID` varchar(255) NOT NULL,
  `SSYNC_REF_USER_GRUP_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUGRUP_ID`),
  KEY `IDX_CLUD_USER_GRUP_01` (`SCUGRUP_ID`,`SCLUD_ID`),
  KEY `IDX_CLUD_USER_GRUP_02` (`SREF_USER_GRUP_ID`,`SCLUD_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_GRUP_ITEM`;
CREATE TABLE `TB_CLUD_USER_GRUP_ITEM` (
  `ICUGITEM_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SUSER_GRUP_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICUGITEM_NO`),
  KEY `IDX_CLUD_USER_GRUP_ITEM_01` (`SUSER_GRUP_ID`),
  KEY `IDX_CLUD_USER_GRUP_ITEM_02` (`SCLUD_ID`,`SCLUD_USER_ID`),
  KEY `IDX_CLUD_USER_GRUP_ITEM_03` (`SCLUD_USER_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_PLGE_ITEM`;
CREATE TABLE `TB_CLUD_USER_PLGE_ITEM` (
  `SCUPITEM_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_APRV_ID` varchar(255) NOT NULL,
  `SPLGE_ID` varchar(255) NOT NULL,
  `STITLE` varchar(255) NOT NULL,
  `SATTR1` varchar(255) NOT NULL,
  `SATTR2` varchar(255) NOT NULL,
  `SATTR3` varchar(255) NOT NULL,
  `SATTR4` varchar(255) NOT NULL,
  `SATTR5` varchar(255) NOT NULL,
  `SATTR6` varchar(255) NOT NULL,
  `SATTR7` varchar(255) NOT NULL,
  `SATTR8` varchar(255) NOT NULL,
  `SDESC` longtext NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUPITEM_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_SYNC`;
CREATE TABLE `TB_CLUD_USER_SYNC` (
  `SCUSYNC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUSYNC_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_SYNC_API`;
CREATE TABLE `TB_CLUD_USER_SYNC_API` (
    `SCUSAPI_ID` VARCHAR(255) NOT NULL,
    `SCLUD_USER_SYNC_ID` VARCHAR(255) NOT NULL,
    `SCLUD_ID` VARCHAR(255) NOT NULL,
    `SSRC_ALLW_CD` VARCHAR(255) NOT NULL,
    `SSRC_IP_ARR` VARCHAR(500) NOT NULL,
    `SAPI_KEY` VARCHAR(255) NOT NULL,
    `SAPI_SCRT` VARCHAR(255) NOT NULL,
    `SAPI_TYPE_CD` VARCHAR(255) NOT NULL,
    `SAPI_URL` VARCHAR(255) NOT NULL,
    `SSYNC_DLTD_USER_YN` VARCHAR(255) NOT NULL,
    `SSYNC_UPDT_USER_YN` VARCHAR(255) NOT NULL,
    `SSYNC_FRCD_UPDT_USER_YN` VARCHAR(255) NOT NULL,
    `SUSER_SYNC_ENDPOINT_URI` VARCHAR(255) NOT NULL,
    `SUSER_LOGN_ID_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_NM_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_EMAL_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_CELL_PHON_NO_FILD_NM` VARCHAR(255) NOT NULL,
    `SREL_USER_GRUP_ID_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_PW_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_PW_SALT_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_PW_CHNG_DT_SYNC_CODE` VARCHAR(255) NOT NULL DEFAULT '',
    `SUSER_ACTIVE_STAT_FILD_NM` VARCHAR(255) NOT NULL DEFAULT '',
    `SUSER_ACTIVE_STAT_CD` VARCHAR(255) NOT NULL DEFAULT '',
    `SUSER_INIT_STAT_CD` VARCHAR(255) NOT NULL DEFAULT 'C_USABLE',
    `SUSER_GRUP_SYNC_YN` VARCHAR(255) NOT NULL,
    `SSYNC_DLTD_USER_GRUP_YN` VARCHAR(255) NOT NULL,
    `SSYNC_UPDT_USER_GRUP_YN` VARCHAR(255) NOT NULL,
    `SUSER_GRUP_SYNC_ENDPOINT_URI` VARCHAR(255) NOT NULL,
    `SUSER_GRUP_ID_FILD_NM` VARCHAR(255) NOT NULL,
    `SREF_USER_GRUP_ID_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_GRUP_NM_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_GRUP_SORT_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_GRUP_ACTIVE_STAT_FILD_NM` VARCHAR(255) NOT NULL DEFAULT '',
    `SUSER_GRUP_ACTIVE_STAT_CD` VARCHAR(255) NOT NULL DEFAULT '',
    `SUSER_GRUP_ROOT_ID` VARCHAR(255) NOT NULL,
    `SUSER_GRUP_ROOT_SYNC_ID` VARCHAR(255) NOT NULL,
    `SBRTH_ID_FILD_NM` VARCHAR(255) NOT NULL,
    `SUSER_FLAG_FILD_NM` VARCHAR(255) NOT NULL,
    `SUNQ_ID_FILD_NM` VARCHAR(255) NOT NULL,
    `SEXEC_DT` VARCHAR(255) NOT NULL,
    `SEXEC_STAT_CD` VARCHAR(255) NOT NULL,
    `SEXEC_LOG` MEDIUMTEXT NOT NULL,
    PRIMARY KEY (`SCUSAPI_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_SYNC_DB`;
CREATE TABLE `TB_CLUD_USER_SYNC_DB` (
  `SCUSDB_ID` varchar(255) NOT NULL,
  `SCLUD_USER_SYNC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SDB_TYPE_CD` varchar(255) NOT NULL,
  `SDB_IP` varchar(255) NOT NULL,
  `SDB_PORT` varchar(255) NOT NULL,
  `SDB_USER_ID` varchar(255) NOT NULL,
  `SDB_USER_PW` varchar(255) NOT NULL,
  `SDB_NM` varchar(255) NOT NULL,
  `SSYNC_DLTD_USER_YN` varchar(255) NOT NULL,
  `SSYNC_UPDT_USER_YN` varchar(255) NOT NULL,
  `SSYNC_FRCD_UPDT_USER_YN` varchar(255) NOT NULL,
  `SUSER_SYNC_TABL_NM` varchar(255) NOT NULL,
  `SUSER_LOGN_ID_FILD_NM` varchar(255) NOT NULL,
  `SUSER_NM_FILD_NM` varchar(255) NOT NULL,
  `SUSER_EMAL_FILD_NM` varchar(255) NOT NULL,
  `SUSER_CELL_PHON_NO_FILD_NM` varchar(255) NOT NULL,
  `SREL_USER_GRUP_ID_FILD_NM` varchar(255) NOT NULL,
  `SUSER_PW_FILD_NM` varchar(255) NOT NULL,
  `SUSER_PW_SALT_FILD_NM` varchar(255) NOT NULL,
  `SUSER_PW_CHNG_DT_SYNC_CODE` varchar(255) NOT NULL DEFAULT '',
  `SUSER_INIT_STAT_CD` varchar(255) NOT NULL DEFAULT 'C_USABLE',
  `SUSER_GRUP_SYNC_YN` varchar(255) NOT NULL,
  `SSYNC_DLTD_USER_GRUP_YN` varchar(255) NOT NULL,
  `SSYNC_UPDT_USER_GRUP_YN` varchar(255) NOT NULL,
  `SUSER_GRUP_SYNC_TABL_NM` varchar(255) NOT NULL,
  `SUSER_GRUP_ID_FILD_NM` varchar(255) NOT NULL,
  `SREF_USER_GRUP_ID_FILD_NM` varchar(255) NOT NULL,
  `SUSER_GRUP_NM_FILD_NM` varchar(255) NOT NULL,
  `SUSER_GRUP_SORT_FILD_NM` varchar(255) NOT NULL,
  `SUSER_GRUP_ROOT_ID` varchar(255) NOT NULL,
  `SUSER_GRUP_ROOT_SYNC_ID` varchar(255) NOT NULL,
  `SSALT` varchar(255) NOT NULL DEFAULT '',
  `SDATA_ENCR_KEY` text NOT NULL DEFAULT '',
  `SDATA_ENCR_IV` text NOT NULL DEFAULT '',
  `SEXEC_DT` varchar(255) NOT NULL,
  `SEXEC_STAT_CD` varchar(255) NOT NULL,
  `SEXEC_LOG` mediumtext NOT NULL,
  PRIMARY KEY (`SCUSDB_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_SYNC_LOG`;
CREATE TABLE `TB_CLUD_USER_SYNC_LOG` (
  `SCUSLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCUSYNC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SSYNC_DATA` longtext NOT NULL,
  `SLOG` longtext NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUSLOG_NO`)
);

DROP TABLE IF EXISTS `TB_CNCT_DISC_CTRL`;
CREATE TABLE `TB_CNCT_DISC_CTRL` (
  `SCDCTRL_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCDCTRL_ID`)
);

DROP TABLE IF EXISTS `TB_CNCT_RJCT_CTRL`;
CREATE TABLE `TB_CNCT_RJCT_CTRL` (
  `SCRCTRL_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCRCTRL_ID`)
);

DROP TABLE IF EXISTS `TB_CNTR`;
CREATE TABLE `TB_CNTR` (
  `SCNTR_ID` varchar(255) NOT NULL,
  `SCNTR_NM` varchar(255) NOT NULL,
  `ISORT` bigint(20) NOT NULL,
  `SDESC` varchar(4000) NOT NULL,
  PRIMARY KEY (`SCNTR_ID`)
);

DROP TABLE IF EXISTS `TB_CODE`;
CREATE TABLE `TB_CODE` (
  `ICODE_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCODE_ID` varchar(255) NOT NULL,
  `SREF_CODE_ID` varchar(255) NOT NULL,
  `SCODE_NM` varchar(4000) NOT NULL,
  `ISORT` bigint(20) NOT NULL,
  `SDESC` varchar(4000) NOT NULL,
  `SATTR1` varchar(1000) NOT NULL,
  `SATTR2` varchar(1000) NOT NULL,
  `SATTR3` varchar(1000) NOT NULL,
  `SATTR4` varchar(1000) NOT NULL,
  `SATTR5` varchar(1000) NOT NULL,
  PRIMARY KEY (`ICODE_NO`),
  UNIQUE KEY `SCODE_ID` (`SCODE_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_CTRL_FLOW_ID_Q`;
CREATE TABLE `TB_CORE_CTRL_FLOW_ID_Q` (
  `SCCFIQ_ID` varchar(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`SCCFIQ_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_CTRL_FLOW_MSTR`;
CREATE TABLE `TB_CORE_CTRL_FLOW_MSTR` (
  `SCCFMSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SFLOW_TYPE_CD` varchar(255) NOT NULL,
  `SFLOW_VRSN` varchar(255) NOT NULL,
  PRIMARY KEY (`SCCFMSTR_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_DATA_FLOW`;
CREATE TABLE `TB_CORE_DATA_FLOW` (
  `SCDFLOW_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SAPP_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SROUT_PLCY_ID` varchar(255) NOT NULL,
  `SCORE_DEVC_TUNL_ID` varchar(255) NOT NULL,
  `SCORE_GW_TUNL_ID` varchar(255) NOT NULL,
  `SSRC_GW_ID` varchar(255) NOT NULL,
  `SITMD_GW_ID` varchar(255) NOT NULL,
  `SDEST_GW_ID` varchar(255) NOT NULL,
  `SPRTC_CD` varchar(255) NOT NULL,
  `SFLOW_PTCL_CD` varchar(255) NOT NULL,
  `STUNL_MODE_CD` varchar(255) NOT NULL,
  `SENCR_ALGO_CD` varchar(255) NOT NULL,
  `SSRC_PROC_ID` varchar(255) NOT NULL,
  `SSRC_APP_ID` varchar(255) NOT NULL,
  `SSRC_APP_EXEC_PATH_ARR` varchar(1000) NOT NULL,
  `SDEST_URL` varchar(1000) NOT NULL,
  `SVRFY_SRC_IP_YN` varchar(255) NOT NULL,
  `SVRTL_IP` varchar(255) NOT NULL,
  `SSRC_IP` varchar(255) NOT NULL,
  `SSRC_PORT` bigint(20) NOT NULL,
  `SDEST_IP` varchar(255) NOT NULL,
  `SDEST_PORT` bigint(20) NOT NULL,
  `SVRFY_MAC_ADDR_YN` varchar(255) NOT NULL,
  `SSRC_MAC_ADDR` varchar(255) NOT NULL,
  `SGW_NAT_DEST_IP_YN` varchar(255) NOT NULL,
  `SGW_NAT_DEST_IP` varchar(255) NOT NULL,
  `IGW_NAT_DEST_PORT` bigint(20) NOT NULL,
  `SDRVR_LV_ENCR_YN` varchar(255) NOT NULL,
  `SDRVR_LV_ENCR_ALGO_CD` varchar(255) NOT NULL,
  `SDRVR_LV_ENCR_KEY` varchar(255) NOT NULL,
  `SDRVR_LV_OTP_TYPE_CD` varchar(255) NOT NULL,
  `SDRVR_LV_OTP_HASH_TYPE_CD` varchar(255) NOT NULL,
  `SDRVR_LV_OTP_SCRT_KEY` varchar(255) NOT NULL,
  `SISPT_APP_YN` varchar(255) NOT NULL,
  `SISPT_APP_MSTR_ID` varchar(255) NOT NULL,
  `SUSE_ISPT_APP_EXPR_YN` varchar(255) NOT NULL,
  `IISPT_APP_EXPR_TS` bigint(20) NOT NULL,
  `SISPT_APP_STAT_CD` varchar(255) NOT NULL,
  `SMFA_YN` varchar(255) NOT NULL,
  `SUSE_VRFY_MFA_EXPR_YN` varchar(255) NOT NULL,
  `IMFA_EXPR_TS` bigint(20) NOT NULL,
  `SMFA_STAT_CD` varchar(255) NOT NULL,
  `SCRET_ON_AUTH_YN` varchar(255) NOT NULL,
  `SACTV_YN` varchar(255) NOT NULL,
  `SMSTR_YN` varchar(255) NOT NULL,
  `STCP_SSIN_SRFT_YN` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  `IUPDT_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`SCDFLOW_ID`),
  KEY `IDX_CORE_DATA_FLOW_01` (`SCORE_CTRL_FLOW_MSTR_ID`, `SCORE_DEVC_TUNL_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_DATA_FLOW_ID_Q`;
CREATE TABLE `TB_CORE_DATA_FLOW_ID_Q` (
  `SCDFIQ_ID` varchar(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`SCDFIQ_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_DATA_FLOW_LOG`;
CREATE TABLE `TB_CORE_DATA_FLOW_LOG` (
  `ICDFLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCDFLOW_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SAPP_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SROUT_PLCY_ID` varchar(255) NOT NULL,
  `SCORE_DEVC_TUNL_ID` varchar(255) NOT NULL,
  `SCORE_GW_TUNL_ID` varchar(255) NOT NULL,
  `SSRC_GW_ID` varchar(255) NOT NULL,
  `SITMD_GW_ID` varchar(255) NOT NULL,
  `SDEST_GW_ID` varchar(255) NOT NULL,
  `SPRTC_CD` varchar(255) NOT NULL,
  `STUNL_MODE_CD` varchar(255) NOT NULL,
  `SENCR_ALGO_CD` varchar(255) NOT NULL,
  `SSRC_APP_ID` varchar(255) NOT NULL,
  `SSRC_APP_EXEC_PATH_ARR` varchar(1000) NOT NULL,
  `SDEST_URL` varchar(1000) NOT NULL,
  `SVRFY_SRC_IP_YN` varchar(255) NOT NULL,
  `SSRC_IP` varchar(255) NOT NULL,
  `SVRFY_MAC_ADDR_YN` varchar(255) NOT NULL,
  `SSRC_MAC_ADDR` varchar(255) NOT NULL,
  `SGW_NAT_DEST_IP_YN` varchar(255) NOT NULL,
  `SGW_NAT_DEST_IP` varchar(255) NOT NULL,
  `IGW_NAT_DEST_PORT` bigint(20) NOT NULL,
  `SDRVR_LV_ENCR_YN` varchar(255) NOT NULL,
  `SDRVR_LV_ENCR_ALGO_CD` varchar(255) NOT NULL,
  `SDRVR_LV_ENCR_KEY` varchar(255) NOT NULL,
  `SISPT_APP_YN` varchar(255) NOT NULL,
  `SISPT_APP_MSTR_ID` varchar(255) NOT NULL,
  `SUSE_ISPT_APP_EXPR_YN` varchar(255) NOT NULL,
  `IISPT_APP_EXPR_TS` bigint(20) NOT NULL,
  `SISPT_APP_STAT_CD` varchar(255) NOT NULL,
  `SMFA_YN` varchar(255) NOT NULL,
  `SUSE_VRFY_MFA_EXPR_YN` varchar(255) NOT NULL,
  `IMFA_EXPR_TS` bigint(20) NOT NULL,
  `SMFA_STAT_CD` varchar(255) NOT NULL,
  `SCRET_ON_AUTH_YN` varchar(255) NOT NULL,
  `SACTV_YN` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  `IUPDT_TS` bigint(20) NOT NULL,
  `SLOG_TYPE` varchar(255) NOT NULL,
  `SACT_FLOW` varchar(255) NOT NULL,
  `SLOG_DESC` text NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICDFLOG_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_DATA_FLOW_SYNC_Q`;
CREATE TABLE `TB_CORE_DATA_FLOW_SYNC_Q` (
  `ICDFSQ_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SCORE_DATA_FLOW_ID` varchar(255) NOT NULL,
  `SDEST_GW_ID` varchar(255) NOT NULL,
  `SURL` varchar(255) NOT NULL,
  `SDATA` longtext NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `SINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`ICDFSQ_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_DEVC_CTRL_FLOW`;
CREATE TABLE `TB_CORE_DEVC_CTRL_FLOW` (
  `SCDCFLOW_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `SNODE_ID` varchar(255) NOT NULL,
  `SDEVC_TYPE_CD` varchar(255) NOT NULL,
  `SDEVC_IP` varchar(255) NOT NULL,
  `SDEVC_PBLC_IP` varchar(255) NOT NULL,
  `SDEVC_MAC_ADDR` varchar(255) NOT NULL,
  `SDEVC_PRDT_NM` varchar(255) NOT NULL DEFAULT '',
  `SDEVC_PLTF_CD` varchar(255) NOT NULL,
  `SDEVC_PLTF_VRSN` varchar(255) NOT NULL,
  `SDEVC_VRTL_GW_TYPE_CD` varchar(255) NOT NULL,
  `SDEVC_VRTL_GW_VRSN` varchar(255) NOT NULL,
  `SDEVC_HOST_NM` varchar(255) NOT NULL,
  `SDEVC_MODL_NM` varchar(255) NOT NULL,
  `SDEVC_SGNT` varchar(255) NOT NULL,
  `SDEVC_USER_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_IP` varchar(255) NOT NULL,
  `SSRC_NTWK_TYPE_CD` varchar(255) NOT NULL,
  `SSRC_NTWK_WIFI_ROUT_ID` varchar(255) NOT NULL,
  `SSRC_NTWK_MOBL_CRER_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_ISP_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_LOCA_CD_ARR` varchar(500) NOT NULL,
  `SDEVC_VRTL_NTWK_IP` varchar(255) NOT NULL,
  `INTWK_ACCU_SENT_MB` bigint(20) NOT NULL,
  `INTWK_ACCU_RECV_MB` bigint(20) NOT NULL,
  `STEMP_YN` varchar(255) NOT NULL,
  `SSEND_ENCR_KEY` varchar(2000) NOT NULL,
  `SRECV_ENCR_KEY` varchar(2000) NOT NULL,
  `SSIGN_PRIV_KEY` text NOT NULL,
  `SSIGN_PBLC_KEY` text NOT NULL,
  `SOTP_SEED_ID` varchar(255) NOT NULL,
  `SOTP_SEED` varchar(255) NOT NULL,
  `SSECR_MCHN_TYPE_CODE` varchar(255) NOT NULL,
  `SSECR_MCHN_BIN_JSON` mediumtext NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SINVK_USER_STAT_YN` varchar(255) NOT NULL,
  `SUSER_FRST_MFA_TS` bigint(20) NOT NULL,
  `SUSER_MFA_STAT_CD` varchar(255) NOT NULL,
  `IUSER_MFA_EXPR_TS` bigint(20) NOT NULL,
  `SUSER_PW_STAT_CD` varchar(255) NOT NULL,
  `SUSER_AWAY_STAT_CD` varchar(255) NOT NULL,
  `SUSE_USER_EXPR_YN` varchar(255) NOT NULL,
  `SCNCT_APP_FLOW_PLCY_CNT` bigint(20) NOT NULL,
  `SDTCT_ROUT_PLCY_ID_ARR` varchar(500) NOT NULL,
  `SLGG_CD` varchar(255) NOT NULL,
  `SREGN_ID` varchar(255) NOT NULL DEFAULT '',
  `IUSER_EXPR_TS` bigint(20) NOT NULL,
  `ILAST_RFRS_TS` bigint(20) NOT NULL,
  `IITGR_CHCK_TS` bigint(20) NOT NULL,
  `SITGR_CHCK_STAT_CD` varchar(255) NOT NULL,
  `SFORC_DISC_MSG` varchar(500) NOT NULL,
  `SEMGC_USE_LOG_ID` longtext NOT NULL DEFAULT '',
  `SAUTH_LOCL_TO_RMOT_DSKT_YN` varchar(255) NOT NULL,
  `SOVPN_GW_RPC_SRVR_URI` varchar(255) NOT NULL DEFAULT '',
  `SCNCT_VPN_TYPE` varchar(255) NOT NULL DEFAULT '',
  `SFRCD_DISC_RSLT_CD` varchar(255) NOT NULL DEFAULT '',
  `SCLUD_USER_GRUP_ARR` varchar(4000) NOT NULL DEFAULT '',
  `SSMBL_JSON_ARR` mediumtext NOT NULL,
  PRIMARY KEY (`SCDCFLOW_ID`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_001` (`SDEVC_ID`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_002` (`STEMP_YN`, `ILAST_RFRS_TS`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_003` (`SINVK_USER_STAT_YN`, `ICNCT_TS`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_004` (`SUSER_MFA_STAT_CD`, `IUSER_EXPR_TS`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_005` (`SUSE_USER_EXPR_YN`, `IUSER_MFA_EXPR_TS`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_006` (`SFORC_DISC_MSG`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_007` (`SCORE_CTRL_FLOW_MSTR_ID`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_008` (`SCLUD_ID`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_009` (`SLOGN_ID`),
  KEY `IDX_CORE_DEVC_CTRL_FLOW_010` (`SCLUD_ID`, `SCLUD_USER_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_ENCR_KEY_STOR`;
CREATE TABLE `TB_CORE_ENCR_KEY_STOR` (
  `SCEKSTOR_ID` varchar(255) NOT NULL,
  `SSEND_ENCR_KEY` varchar(2000) NOT NULL,
  `SRECV_ENCR_KEY` varchar(2000) NOT NULL,
  `SSIGN_PRVT_KEY` text NOT NULL,
  `SSIGN_PBLC_KEY` text NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCEKSTOR_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_GW`;
CREATE TABLE `TB_CORE_GW` (
  `SCGW_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SINFR_MSTR_ID` varchar(255) NOT NULL,
  `SGW_SERL` varchar(255) NOT NULL,
  `SGW_VRSN` varchar(255) NOT NULL,
  `SGW_HW_MODL_NM` varchar(255) NOT NULL,
  `SHDSK_ENCR_KEY_ID` varchar(255) NOT NULL DEFAULT '',
  `SGW_TUNL_IP` varchar(500) NOT NULL,
  `SSSL_VPN_GW_TUNL_IP` varchar(255) NOT NULL DEFAULT '',
  `SGW_RPC_SRVR_IP` varchar(255) NOT NULL,
  `IGW_RPC_SRVR_PORT` bigint(20) NOT NULL,
  `STUNL_MODE_CD` varchar(255) NOT NULL,
  `SSSL_VPN_TUNL_MODE_CD` varchar(255) NOT NULL DEFAULT '',
  `STUNL_ALGO_CD` varchar(255) NOT NULL,
  `SSSL_VPN_TUNL_ALGO_CD` varchar(255) NOT NULL DEFAULT '',
  `STUNL_AUTH_KEY_EXCN_CD` varchar(255) NOT NULL,
  `SSSL_VPN_TUNL_AUTH_KEY_EXCN_CD` varchar(255) NOT NULL DEFAULT '',
  `STUNL_ALLC_CIDR` text NOT NULL,
  `SSSL_VPN_TUNL_ALLC_CIDR` text NOT NULL DEFAULT '',
  `SDFLT_GW` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_DFLT_GW` varchar(255) NOT NULL DEFAULT '',
  `SIP_SEC_VPN_PATH_TYPE_CD` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_PATH_TYPE_CD` varchar(255) NOT NULL DEFAULT '',
  `SCERT_AUTH_ID` varchar(255) NOT NULL DEFAULT '',
  `SUSE_PRVT_ROOT_CRTF_YN` varchar(255) NOT NULL DEFAULT '',
  `SROOT_PRVT_CRTF` text NOT NULL DEFAULT '',
  `SROOT_PBLC_CRTF` text NOT NULL DEFAULT '',
  `SSRVR_PRVT_CRTF` text NOT NULL DEFAULT '',
  `SSRVR_PBLC_CRTF` text NOT NULL DEFAULT '',
  `SSRVR_NM` varchar(255) NOT NULL DEFAULT '',
  `STUNL_AUTH_TYPE_CD` varchar(50) NOT NULL,
  `SCERT_FILE_BIN` mediumtext NOT NULL,
  `SITGT_INFO` mediumtext NOT NULL,
  `IITGT_CHCK_TS` bigint(20) NOT NULL,
  `ISYNC_TIME_TS` bigint(20) NOT NULL,
  `SGW_HEDR` varchar(255) NOT NULL DEFAULT '',
  `SACCP_ISPT_CTRL_FLOW_PRTC_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACCP_INST_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACCP_INST_GW_HEDR_TYPE_CD` varchar(255) NOT NULL DEFAULT '',
  `SACTP_FRWD_YN` varchar(255) NOT NULL DEFAULT '',
  `SACTP_IP_FRWD_YN` varchar(255) NOT NULL DEFAULT '',
  `SACTP_INST_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACTP_DLTE_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACTP_ISPT_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACSP_FRWD_YN` varchar(255) NOT NULL DEFAULT '',
  `SACSP_INST_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACSP_DLTE_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACSP_ISPT_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACWP_RDRT_YN` varchar(255) NOT NULL DEFAULT '',
  `SACWP_RDRT_URL` varchar(255) NOT NULL DEFAULT '',
  `SACPP_FRWD_YN` varchar(255) NOT NULL DEFAULT '',
  `SACAP_FRWD_YN` varchar(255) NOT NULL DEFAULT '',
  `SACDP_FRWD_YN` varchar(255) NOT NULL DEFAULT '',
  `SACDP_INST_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACDP_DLTE_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACDP_ISPT_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SACNP_FRWD_YN` varchar(255) NOT NULL DEFAULT '',
  `SACNP_INST_GW_HEDR_YN` varchar(255) NOT NULL DEFAULT '',
  `SUSE_STAT_MODE_YN` varchar(255) NOT NULL DEFAULT '',
  `SSTAT_MODE_GW_TUNL_AUTH_USER_NM` varchar(255) NOT NULL DEFAULT '',
  `SSTAT_MODE_GW_TUNL_AUTH_USER_PW` varchar(255) NOT NULL DEFAULT '',
  `SOVPN_GW_RPC_SRVR_URI` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_TRSP_PRTC_CD` varchar(255) NOT NULL DEFAULT '',
  `SOVPN_GW_TUNL_IP` varchar(255) NOT NULL DEFAULT '',
  `IOVPN_GW_TUNL_PORT` bigint(20) NOT NULL,
  `SSSL_VPN_VIP_CIDR` varchar(255) NOT NULL DEFAULT '',
  `SOVPN_PBLC_CRTF` text NOT NULL DEFAULT '',
  `SPRRT_VPN_CD` varchar(255) NOT NULL DEFAULT '',
  `SDATA_FLOW_USE_YN` varchar(255) NOT NULL DEFAULT '',
  `STRST_DEST_NEWK_USE_YN` varchar(255) NOT NULL DEFAULT '',
  `STRST_DEST_NEWK_LOG_YN` varchar(255) NOT NULL DEFAULT '',
  `SRDRC_YN` varchar(255) NOT NULL DEFAULT '',
  `SRDRC_IP` varchar(255) NOT NULL DEFAULT '',
  `IRDRC_PORT` bigint(20) NOT NULL,
  `SRGST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCGW_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_GW_TUNL_AUTH`;
CREATE TABLE `TB_CORE_GW_TUNL_AUTH` (
  `ICGTAUTH_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCORE_GW_ID` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SUSER_PW` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `IEXPR_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`ICGTAUTH_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_GW_UNIT`;
CREATE TABLE `TB_CORE_GW_UNIT` (
  `SCGUNIT_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCGW_ID` varchar(255) NOT NULL,
  `SGW_API_SRVR_IP` varchar(255) NOT NULL,
  `SGW_API_SRVR_PORT` bigint(20) NOT NULL,
  `SHTTPS_YN` varchar(255) NOT NULL,
  `SITGT_INFO` mediumtext NOT NULL DEFAULT '',
  `SGW_SERL` varchar(255) NOT NULL DEFAULT '',
  `SGW_VRSN` varchar(255) NOT NULL DEFAULT '',
  `SGW_HW_MODL_NM` varchar(255) NOT NULL DEFAULT '',
  `SRGST_YN` varchar(255) NOT NULL,
  `SRGST_DT` varchar(255) NOT NULL,
  `SRSCS_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCGUNIT_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_HDSK_ENCR_KEY`;
CREATE TABLE `TB_CORE_HDSK_ENCR_KEY` (
  `SCHEKEY_ID` varchar(255) NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `SSEND_ENCR_KEY` varchar(2000) NOT NULL,
  `SRECV_ENCR_KEY` varchar(2000) NOT NULL,
  `SSIGN_PRIV_KEY` text NOT NULL,
  `SSIGN_PBLC_KEY` text NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUSED_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCHEKEY_ID`),
  KEY `IDX_CORE_HDSK_ENCR_KEY_001` (`STYPE_CD`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_CNFG`;
CREATE TABLE `TB_CORE_INFR_CNFG` (
  `SCICNFG_ID` varchar(255) NOT NULL,
  `SCTRL_CNFG_JSON` mediumtext NOT NULL,
  `SCTRL_META_JSON` mediumtext NOT NULL,
  `SCNSL_CNFG_JSON` mediumtext NOT NULL,
  `SVRTL_GW_CNFG_JSON` mediumtext NOT NULL,
  `SCLUD_GW_CNFG_JSON` mediumtext NOT NULL,
  `SKEY_ENCR_PRVT_KEY` text NOT NULL,
  `SKEY_ENCR_PBLC_KEY` text NOT NULL,
  `SDATA_ENCR_KEY` text NOT NULL,
  `SDATA_ENCR_IV` text NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCICNFG_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_CTRL_CACH_Q`;
CREATE TABLE `TB_CORE_INFR_CTRL_CACH_Q` (
  `ICICCQUE_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCACH_ITEM_CD` varchar(255) NOT NULL,
  `SCLCT_ID` varchar(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`ICICCQUE_NO`),
  KEY `IDX_CORE_INFR_CTRL_CACH_Q_001` (`SCORE_INFR_MSTR_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_EVNT_LOG`;
CREATE TABLE `TB_CORE_INFR_EVNT_LOG` (
  `ICIELOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  `SLOG_CD` varchar(255) NOT NULL,
  `SLOG_NM` varchar(500) NOT NULL,
  `SEVNT_LOG` mediumtext NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICIELOG_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_LCNS`;
CREATE TABLE `TB_CORE_INFR_LCNS` (
  `SCILCNS_ID` varchar(255) NOT NULL,
  `SLCNS_JSON` mediumtext NOT NULL,
  `SLCNS_ID` varchar(255) NOT NULL,
  `SVRFY_KEY` mediumtext NOT NULL,
  `SLCNS_SGNT` mediumtext NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCILCNS_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_MSTR`;
CREATE TABLE `TB_CORE_INFR_MSTR` (
  `SCIMSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SHOST_CORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  `SINFR_TYPE_CD` varchar(255) NOT NULL,
  `SINFR_ISTC_ID` varchar(255) NOT NULL,
  `SOWNR_CD` varchar(255) NOT NULL,
  `SCORE_INFR_PRVS_SPEC_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPLTF_VRSN` varchar(255) NOT NULL,
  `SINFR_NM` varchar(255) NOT NULL,
  `SINFR_NTWK_IP` varchar(255) NOT NULL,
  `SCPU_CLCK` varchar(255) NOT NULL,
  `ICPU_CNT` bigint(20) NOT NULL,
  `ICPU_USGE_RTIO` bigint(20) NOT NULL,
  `IMEM_TTAL_MB` bigint(20) NOT NULL,
  `IDISK_TTAL_MB` bigint(20) NOT NULL,
  `INIC_BDWT_MB` bigint(20) NOT NULL,
  `INIC_SENT_MB_MIN` bigint(20) NOT NULL,
  `INIC_RECV_MB_MIN` bigint(20) NOT NULL,
  `ICTRL_FLOW_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_CNT` bigint(20) NOT NULL,
  `ITUNL_CNT` bigint(20) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SCRET_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCIMSTR_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_MSTR_HSTR`;
CREATE TABLE `TB_CORE_INFR_MSTR_HSTR` (
  `ICIMHSTR_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  `SHOST_CORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  `SINFR_TYPE_CD` varchar(255) NOT NULL,
  `SINFR_ISTC_ID` varchar(255) NOT NULL,
  `SOWNR_CD` varchar(255) NOT NULL,
  `SCORE_INFR_PRVS_SPEC_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPLTF_VRSN` varchar(255) NOT NULL,
  `SINFR_NM` varchar(255) NOT NULL,
  `SINFR_NTWK_IP` varchar(255) NOT NULL,
  `SCPU_CLCK` varchar(255) NOT NULL,
  `ICPU_CNT` bigint(20) NOT NULL,
  `IMEM_TTAL_MB` bigint(20) NOT NULL,
  `IDISK_TTAL_MB` bigint(20) NOT NULL,
  `INIC_BDWT_MB` bigint(20) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINS_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICIMHSTR_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_OTP_SEED`;
CREATE TABLE `TB_CORE_OTP_SEED` (
  `SCOSEED_ID` varchar(255) NOT NULL,
  `SOTP_KEY` varchar(255) NOT NULL,
  `IUSE_CNT` bigint(20) NOT NULL,
  PRIMARY KEY (`SCOSEED_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_TUNL`;
CREATE TABLE `TB_CORE_TUNL` (
  `SCTUNL_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STSP_GW_ID` varchar(255) NOT NULL,
  `STEP_GW_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SROUT_PLCY_ID` varchar(255) NOT NULL,
  `STSP_IP` varchar(255) NOT NULL,
  `STEP_IP` varchar(500) NOT NULL,
  `STUNL_MODE_CD` varchar(255) NOT NULL,
  `STUNL_ALGO_CD` varchar(255) NOT NULL,
  `STUNL_AUTH_KEY_EXCN_CD` varchar(255) NOT NULL,
  `STUNL_AUTH_SRVR_PBLC_CRTF` text NOT NULL,
  `SSSL_VPN_TEP_IP` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_TUNL_MODE_CD` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_TUNL_ALGO_CD` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_TUNL_AUTH_KEY_EXCN_CD` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_TUNL_AUTH_SRVR_PBLC_CRTF` text NOT NULL DEFAULT '',
  `SSSL_VPN_TUNL_TLS_CRPT_KEY` text NOT NULL DEFAULT '',
  `SSSL_VPN_TEP_PORT` bigint(20) NOT NULL,
  `SSSL_VPN_TRSP_PRTC_CD` varchar(255) NOT NULL DEFAULT 'C_TCP',
  `STUNL_AUTH_TYPE_CD` varchar(255) NOT NULL,
  `ICORE_GW_TUNL_AUTH_NO` bigint(20) NOT NULL,
  `STUNL_AUTH_USER_NM` varchar(255) NOT NULL,
  `STUNL_AUTH_USER_PW` varchar(255) NOT NULL,
  `STUNL_ALLC_CIDR` text NOT NULL,
  `SSSL_VPN_TUNL_ALLC_CIDR` text NOT NULL DEFAULT '',
  `SDATA_FLOW_ROUT_CIDR_ARR` text NOT NULL,
  `SDFLT_GW` varchar(255) NOT NULL DEFAULT '',
  `SSSL_VPN_DFLT_GW` varchar(255) NOT NULL DEFAULT '',
  `SUSE_PRVT_DNS_YN` varchar(255) NOT NULL,
  `SPRVT_DNS_PRMR_IP` varchar(255) NOT NULL,
  `SPRVT_DNS_SCND_IP` varchar(255) NOT NULL,
  `SLEFT_ID` varchar(255) NOT NULL DEFAULT '',
  `ISENT_MB_PER_MIN` bigint(20) NOT NULL,
  `IRECV_MB_PER_MIN` bigint(20) NOT NULL,
  `ISENT_ACCU_MB` bigint(20) NOT NULL,
  `IRECV_ACCU_MB` bigint(20) NOT NULL,
  `ICRET_TS` bigint(20) NOT NULL,
  `IUPDT_TS` bigint(20) NOT NULL,
  `ICNCT_RETR_CNT` bigint(20) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SPRRT_VPN_CD` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`SCTUNL_ID`),
  KEY `IDX_CORE_TUNL_01` (`SCORE_CTRL_FLOW_MSTR_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_TUNL_ID_Q`;
CREATE TABLE `TB_CORE_TUNL_ID_Q` (
  `SCTIQ_ID` varchar(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`SCTIQ_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_TUNL_LOG`;
CREATE TABLE `TB_CORE_TUNL_LOG` (
  `ICTLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCTUNL_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STSP_GW_ID` varchar(255) NOT NULL,
  `STEP_GW_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SROUT_PLCY_ID` varchar(255) NOT NULL,
  `STSP_IP` varchar(255) NOT NULL,
  `STEP_IP` varchar(500) NOT NULL,
  `STUNL_MODE_CD` varchar(255) NOT NULL,
  `STUNL_ALGO_CD` varchar(255) NOT NULL,
  `STUNL_AUTH_KEY_EXCN_CD` varchar(255) NOT NULL,
  `STUNL_AUTH_SRVR_PBLC_CRTF` text NOT NULL,
  `STUNL_AUTH_TYPE_CD` varchar(255) NOT NULL,
  `ICORE_GW_TUNL_AUTH_NO` bigint(20) NOT NULL,
  `STUNL_AUTH_USER_NM` varchar(255) NOT NULL,
  `STUNL_ALLC_CIDR` text NOT NULL,
  `SDATA_FLOW_ROUT_CIDR_ARR` text NOT NULL,
  `SUSE_PRVT_DNS_YN` varchar(255) NOT NULL,
  `SPRVT_DNS_PRMR_IP` varchar(255) NOT NULL,
  `SPRVT_DNS_SCND_IP` varchar(255) NOT NULL,
  `ISENT_MB_PER_MIN` bigint(20) NOT NULL,
  `IRECV_MB_PER_MIN` bigint(20) NOT NULL,
  `ISENT_ACCU_MB` bigint(20) NOT NULL,
  `IRECV_ACCU_MB` bigint(20) NOT NULL,
  `ICRET_TS` bigint(20) NOT NULL,
  `IUPDT_TS` bigint(20) NOT NULL,
  `ICNCT_RETR_CNT` bigint(20) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SLOG_TYPE` varchar(255) NOT NULL,
  `SACT_FLOW` varchar(255) NOT NULL,
  `SLOG_DESC` text NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICTLOG_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_USER`;
CREATE TABLE `TB_CORE_USER` (
  `SCUSER_ID` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SLOGN_PW` varchar(255) NOT NULL,
  `SLOGN_PW_CHNG_DT` varchar(255) NOT NULL,
  `SLAST_LOGN_DT` varchar(255) NOT NULL,
  `SLAST_LOGN_IP` varchar(255) NOT NULL,
  `SLOGN_RTRY_CNT` bigint(20) NOT NULL,
  `ILOGN_RSTR_EXPR_TS` bigint(20) NOT NULL,
  `SEMAL_ADDR` varchar(255) NOT NULL,
  `SCELL_PHON_NO` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SUSE_ALLW_IP_YN` varchar(255) NOT NULL,
  `SALLW_IP_ARR` varchar(255) NOT NULL,
  `SUSER_TYPE_CD` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SSALT` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCUSER_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_USER_ACT_LOG`;
CREATE TABLE `TB_CORE_USER_ACT_LOG` (
  `ICUALOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCORE_USER_ID` varchar(255) NOT NULL,
  `SCORE_USER_NM` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SACT_CD` varchar(255) NOT NULL,
  `SACT_DC` longtext NOT NULL,
  `SACT_DC_EN` longtext NULL,
  `SACT_DC_JP` longtext NULL,
  `SACT_IP` varchar(255) NOT NULL,
  `SMAIN_MENU_CD` varchar(255) NOT NULL,
  `SMAIN_OBJ_ID` varchar(255) NOT NULL,
  `SREF_MENU_CD` varchar(255) NOT NULL,
  `SREF_OBJ_ID` varchar(255) NOT NULL,
  `SMAIN_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SINST_UT` int(11) NOT NULL,
  PRIMARY KEY (`ICUALOG_NO`),
  KEY `IDX_CORE_USER_ACT_LOG_01` (`ICUALOG_NO`),
  KEY `IDX_CORE_USER_ACT_LOG_02` (`SINST_UT`,`SMAIN_YN`),
  KEY `IDX_CORE_USER_ACT_LOG_03` (`SMAIN_MENU_CD`,`SMAIN_OBJ_ID`),
  KEY `IDX_CORE_USER_ACT_LOG_04` (`SREF_MENU_CD`,`SREF_OBJ_ID`),
  KEY `IDX_CORE_USER_ACT_LOG_05` (`SACT_CD`)
);

DROP TABLE IF EXISTS `TB_CORE_USER_ACT_LEGACY_LOG`;
CREATE TABLE `TB_CORE_USER_ACT_LEGACY_LOG` (
  `ICUALOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCORE_USER_ID` varchar(255) NOT NULL,
  `SCORE_USER_NM` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SACT_CD` varchar(255) NOT NULL,
  `SACT_DC` longtext NOT NULL,
  `SACT_DC_EN` longtext NULL,
  `SACT_DC_JP` longtext NULL,
  `SACT_IP` varchar(255) NOT NULL,
  `SMAIN_MENU_CD` varchar(255) NOT NULL,
  `SMAIN_OBJ_ID` varchar(255) NOT NULL,
  `SREF_MENU_CD` varchar(255) NOT NULL,
  `SREF_OBJ_ID` varchar(255) NOT NULL,
  `SMAIN_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SINST_UT` int(11) NOT NULL,
  PRIMARY KEY (`ICUALOG_NO`),
  KEY `IDX_CORE_USER_ACT_LEGACY_LOG_01` (`ICUALOG_NO`),
  KEY `IDX_CORE_USER_ACT_LEGACY_LOG_02` (`SINST_UT`,`SMAIN_YN`),
  KEY `IDX_CORE_USER_ACT_LEGACY_LOG_03` (`SMAIN_MENU_CD`,`SMAIN_OBJ_ID`),
  KEY `IDX_CORE_USER_ACT_LEGACY_LOG_04` (`SREF_MENU_CD`,`SREF_OBJ_ID`),
  KEY `IDX_CORE_USER_ACT_LEGACY_LOG_05` (`SACT_CD`)
);

DROP TABLE IF EXISTS `TB_CORE_USER_ALLW_MENU`;
CREATE TABLE `TB_CORE_USER_ALLW_MENU` (
  `ICUAMENU_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCORE_USER_ID` varchar(255) NOT NULL,
  `SMENU_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ICUAMENU_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_USER_AUTH`;
CREATE TABLE `TB_CORE_USER_AUTH` (
  `ICUAUTH_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `STYPE_CD` varchar(255) NOT NULL,
  `SCORE_USER_ID` varchar(255) NOT NULL,
  `SAUTH_ID` varchar(255) NOT NULL,
  `SOTP` varchar(255) NOT NULL,
  `IRETR_CNT` bigint(20) NOT NULL,
  `SRQST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ICUAUTH_NO`)
);

DROP TABLE IF EXISTS `TB_CORE_VRTL_GW_DSTR`;
CREATE TABLE `TB_CORE_VRTL_GW_DSTR` (
  `SCVGDSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SVRTL_GW_TYPE_CD` varchar(255) NOT NULL,
  `SVRSN` varchar(255) NOT NULL,
  `SFRCD_UPDT_YN` varchar(255) NOT NULL,
  `SNOTI_UPDT_YN` varchar(255) NOT NULL,
  `SRELS_NOTE` mediumtext NOT NULL,
  `SISPT_CNDT_JSON` mediumtext NOT NULL,
  `SDSTR_URL` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SCVGDSTR_ID`)
);

DROP TABLE IF EXISTS `TB_DEVC_ITGR_LOG`;
CREATE TABLE `TB_DEVC_ITGR_LOG` (
  `IDILOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SDEVC_REAL_ID` varchar(100) NOT NULL,
  `SDESC` varchar(4000) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IDILOG_NO`),
  KEY `IDX_TB_DEVC_ITGR_LOG_001` (`SDEVC_REAL_ID`,`SINST_DT`,`SSTAT_CD`)
);

DROP TABLE IF EXISTS `TB_EMGC_USE_LOG`;
CREATE TABLE `TB_EMGC_USE_LOG` (
  `SEULOG_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_APRV_ID` varchar(255) NOT NULL,
  `SCORE_DEVC_CTRL_FLOW_ID` varchar(255) NOT NULL,
  `IUSE_STRT_TS` bigint(20) NOT NULL DEFAULT 0,
  `IUSE_END_TS` bigint(20) NOT NULL DEFAULT 0,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SEULOG_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC`;
CREATE TABLE `TB_EVDC` (
  `IEVDC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SEVDC_TYPE_CD` varchar(255) NOT NULL,
  `SRISK_LV_CD` varchar(255) NOT NULL,
  `SCTRL_FLOW_EXCP_CD` varchar(255) NOT NULL,
  `SCTRL_FLOW_EXCP_CD_NM` varchar(1000) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SDEVC_TYPE_CD` varchar(255) NOT NULL,
  `SDEVC_MAC_ADDR` varchar(255) NOT NULL,
  `SDEVC_PLTF_CD` varchar(255) NOT NULL,
  `SDEVC_PLTF_VRSN` varchar(255) NOT NULL,
  `SDEVC_VRTL_GW_TYPE_CD` varchar(255) NOT NULL,
  `SDEVC_VRTL_GW_VRSN` varchar(255) NOT NULL,
  `SDEVC_HOST_NM` varchar(255) NOT NULL,
  `SDEVC_MODL_NM` varchar(255) NOT NULL,
  `SDEVC_USER_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_IP` varchar(255) NOT NULL,
  `SSRC_NTWK_TYPE_CD` varchar(255) NOT NULL,
  `SSRC_NTWK_WIFI_ROUT_ID` varchar(255) NOT NULL,
  `SSRC_NTWK_MOBL_CRER_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_ISP_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_LOCA_CD_ARR` varchar(500) NOT NULL,
  `SDEVC_VRTL_NTWK_IP` varchar(255) NOT NULL,
  `SEVDC_ADTN_DATA_JSON` mediumtext NOT NULL,
  `IEVDC_DATA_FLOW_LOG_NO` bigint(20) NOT NULL,
  `SDATA_FLOW_APP_ID` varchar(255) NOT NULL,
  `SDATA_FLOW_DEST_URL` varchar(1000) NOT NULL,
  `IEVDC_TUNL_LOG_NO` bigint(20) NOT NULL,
  `SDEL_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SINST_UT` int(11) NOT NULL,
  PRIMARY KEY (`IEVDC_NO`),
  KEY `IDX_EVDC_01` (`IEVDC_NO`),
  KEY `IDX_EVDC_02` (`SCLUD_ID`,`SINST_UT`),
  KEY `IDX_EVDC_03` (`SCLUD_ID`,`SEVDC_ROOT_ID`),
  KEY `IDX_EVDC_04` (`SEVDC_TYPE_CD`,`SCLUD_ID`),
  KEY `IDX_EVDC_05` (`SEVDC_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_LEGACY`;
CREATE TABLE `TB_EVDC_LEGACY` (
  `IEVDC_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SEVDC_TYPE_CD` varchar(255) NOT NULL,
  `SRISK_LV_CD` varchar(255) NOT NULL,
  `SCTRL_FLOW_EXCP_CD` varchar(255) NOT NULL,
  `SCTRL_FLOW_EXCP_CD_NM` varchar(1000) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SDEVC_TYPE_CD` varchar(255) NOT NULL,
  `SDEVC_MAC_ADDR` varchar(255) NOT NULL,
  `SDEVC_PLTF_CD` varchar(255) NOT NULL,
  `SDEVC_PLTF_VRSN` varchar(255) NOT NULL,
  `SDEVC_VRTL_GW_TYPE_CD` varchar(255) NOT NULL,
  `SDEVC_VRTL_GW_VRSN` varchar(255) NOT NULL,
  `SDEVC_HOST_NM` varchar(255) NOT NULL,
  `SDEVC_MODL_NM` varchar(255) NOT NULL,
  `SDEVC_USER_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_IP` varchar(255) NOT NULL,
  `SSRC_NTWK_TYPE_CD` varchar(255) NOT NULL,
  `SSRC_NTWK_WIFI_ROUT_ID` varchar(255) NOT NULL,
  `SSRC_NTWK_MOBL_CRER_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_ISP_NM` varchar(255) NOT NULL,
  `SSRC_NTWK_LOCA_CD_ARR` varchar(500) NOT NULL,
  `SDEVC_VRTL_NTWK_IP` varchar(255) NOT NULL,
  `SEVDC_ADTN_DATA_JSON` mediumtext NOT NULL,
  `IEVDC_DATA_FLOW_LOG_NO` bigint(20) NOT NULL,
  `SDATA_FLOW_APP_ID` varchar(255) NOT NULL,
  `SDATA_FLOW_DEST_URL` varchar(1000) NOT NULL,
  `IEVDC_TUNL_LOG_NO` bigint(20) NOT NULL,
  `SDEL_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SINST_UT` int(11) NOT NULL,
  PRIMARY KEY (`IEVDC_NO`),
  KEY `IDX_EVDC_LEGACY_01` (`IEVDC_NO`),
  KEY `IDX_EVDC_LEGACY_02` (`SCLUD_ID`,`SINST_UT`),
  KEY `IDX_EVDC_LEGACY_03` (`SCLUD_ID`,`SEVDC_ROOT_ID`),
  KEY `IDX_EVDC_LEGACY_04` (`SEVDC_TYPE_CD`,`SCLUD_ID`),
  KEY `IDX_EVDC_LEGACY_05` (`SEVDC_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_APLY_PLCY`;
CREATE TABLE `TB_EVDC_APLY_PLCY` (
  `IEAPLCY_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SJSON` longtext NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IEAPLCY_NO`)
);

DROP TABLE IF EXISTS `TB_EVDC_AUDT`;
CREATE TABLE `TB_EVDC_AUDT` (
  `IEAUDT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SEVDC_ID` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SDEVC_PLTF_CD` varchar(255) NOT NULL,
  `SDEVC_MODL_NM` varchar(255) NOT NULL,
  `SUSE_VRTL_DSKT_YN` varchar(255) NOT NULL,
  `SCTRL_FLOW_DISC_RISK_LV_CD` varchar(255) NOT NULL,
  `IBHVR_CTRL_CNT` bigint(20) NOT NULL,
  `IEVDC_CNT` bigint(20) NOT NULL,
  `SAUDT_STAT_CD` varchar(255) NOT NULL,
  `SAUDT_DC` text NOT NULL,
  `SAUDT_DT` varchar(255) NOT NULL,
  `SCNCT_DT` varchar(255) NOT NULL,
  `SDISC_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IEAUDT_NO`)
);

DROP TABLE IF EXISTS `TB_EVDC_CLUD_GW_DATA_PCKT_DROP_LOG`;
CREATE TABLE `TB_EVDC_CLUD_GW_DATA_PCKT_DROP_LOG` (
  `IECGDPDLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCORE_GW_ID` varchar(255) NOT NULL,
  `SNODE_IP` varchar(255) NOT NULL,
  `SNODE_MAC_ADDR` varchar(255) NOT NULL,
  `SDROP_RESN_CD` varchar(255) NOT NULL,
  `SDROP_LOG` mediumtext NOT NULL,
  `SDROP_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IECGDPDLOG_NO`)
);

DROP TABLE IF EXISTS `TB_EVDC_DATA_FLOW_LOG`;
CREATE TABLE `TB_EVDC_DATA_FLOW_LOG` (
  `IEDFLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCORE_DATA_FLOW_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SAPP_MSTR_ID` varchar(255) NOT NULL,
  `SAPP_ID` varchar(255) NOT NULL,
  `SPRTC_CD` varchar(255) NOT NULL,
  `STUNL_ID` varchar(255) NOT NULL,
  `SFLOW_DRVR_LV_ENCR_ALGO_CD` varchar(255) NOT NULL,
  `SSRC_IP` varchar(255) NOT NULL,
  `SVRTL_IP` varchar(255) NOT NULL,
  `SDEST_URL` varchar(1000) NOT NULL,
  `SISPT_APP_YN` varchar(255) NOT NULL,
  `SMFA_YN` varchar(255) NOT NULL,
  `SCRET_ON_AUTH_YN` varchar(255) NOT NULL,
  PRIMARY KEY (`IEDFLOG_NO`) USING BTREE,
  KEY `IDX_EVDC_DATA_FLOW_LOG_001` (`SCLUD_ID`,`SEVDC_ROOT_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_DATA_FLOW_ROUT`;
CREATE TABLE `TB_EVDC_DATA_FLOW_ROUT` (
  `IEDFLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SDATA_FLOW_ROUT_CIDR_ARR` text NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IEDFLOG_NO`),
  KEY `IDX_EVDC_DATA_FLOW_ROUT_001` (`SCLUD_ID`,`SEVDC_ROOT_ID`),
  KEY `IDX_EVDC_DATA_FLOW_ROUT_002` (`SEVDC_ROOT_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_EXEC_APP`;
CREATE TABLE `TB_EVDC_EXEC_APP` (
  `IEEAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SLOG_JSON` mediumtext NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IEEAPP_NO`),
  KEY `IDX_EVDC_EXEC_APP_001` (`SCLUD_ID`,`SEVDC_ROOT_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_INST_APP`;
CREATE TABLE `TB_EVDC_INST_APP` (
  `IEEAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SLOG_JSON` mediumtext NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IEEAPP_NO`),
  KEY `IDX_EVDC_INST_APP_001` (`SCLUD_ID`,`SEVDC_ROOT_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_NTWK_LSTN_PORT`;
CREATE TABLE `TB_EVDC_NTWK_LSTN_PORT` (
  `IENLSTN_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SLOG_JSON` mediumtext NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IENLSTN_NO`),
  KEY `IDX_EVDC_NTWK_LSTN_PORT_001` (`SCLUD_ID`,`SEVDC_ROOT_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_RISK_AUDT`;
CREATE TABLE `TB_EVDC_RISK_AUDT` (
  `SERAUDT_ID` varchar(255) NOT NULL,
  `SEVDC_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SAUDT_RSLT_CD` varchar(255) NOT NULL,
  `SAUDT_RSLT_JSON` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SERAUDT_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_RISK_AUDT_LOG`;
CREATE TABLE `TB_EVDC_RISK_AUDT_LOG` (
  `IERAUDT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SLOG_JSON` mediumtext NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IERAUDT_NO`),
  KEY `IDX_EVDC_RISK_AUDT_LOG_001` (`SCLUD_ID`,`SEVDC_ROOT_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_TUNL_LOG`;
CREATE TABLE `TB_EVDC_TUNL_LOG` (
  `IETUNL_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `STUNL_ID` varchar(255) NOT NULL,
  `STEP_IP` varchar(255) NOT NULL,
  `SGW_ID` varchar(255) NOT NULL,
  `SGW_NM` varchar(255) NOT NULL,
  `STUNL_MODE_CD` varchar(255) NOT NULL,
  `SENCR_ALGO_CD` varchar(255) NOT NULL,
  `STUNL_ALLC_CIDR` varchar(255) NOT NULL,
  `SFAIL_RESN_CD` varchar(255) NOT NULL,
  `SFAIL_RESN` varchar(1000) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  PRIMARY KEY (`IETUNL_NO`),
  KEY `IDX_EVDC_TUNL_LOG_01` (`SEVDC_ROOT_ID`, `STUNL_ID`)
);

DROP TABLE IF EXISTS `TB_EVDC_VRTL_GW_DATA_PCKT_DROP_LOG`;
CREATE TABLE `TB_EVDC_VRTL_GW_DATA_PCKT_DROP_LOG` (
  `IEVGDPDLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEVDC_ROOT_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SDEVC_ID` varchar(255) NOT NULL,
  `ICNCT_TS` bigint(20) NOT NULL,
  `SLOG_JSON` mediumtext NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IEVGDPDLOG_NO`)
);

DROP TABLE IF EXISTS `TB_EXCP_LOG`;
CREATE TABLE `TB_EXCP_LOG` (
  `IELOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SGBN_CD` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCGW_ID` varchar(255) NOT NULL,
  `SCGUNIT_ID` varchar(255) NOT NULL,
  `SFNC_NM` varchar(255) NOT NULL,
  `STITLE` varchar(1000) NOT NULL,
  `SMSG` text NOT NULL,
  `SCUSER_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IELOG_NO`)
);

DROP TABLE IF EXISTS `TB_FILE_BIN`;
CREATE TABLE `TB_FILE_BIN` (
  `SFBIN_ID` varchar(255) NOT NULL,
  `STRGT_CD` varchar(255) NOT NULL,
  `STRGT_ID` varchar(255) NOT NULL,
  `SFILE_NM` varchar(255) NOT NULL,
  `SFILE_NM_EXT` varchar(255) NOT NULL,
  `SFILE_BIN` longblob NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SFBIN_ID`)
);

DROP TABLE IF EXISTS `TB_FLOW_PLCY_ALLW_APP`;
CREATE TABLE `TB_FLOW_PLCY_ALLW_APP` (
  `IFPAAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SALLW_APP_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IFPAAPP_NO`),
  KEY `IDX_FLOW_PLCY_ALLW_APP_001` (`SCLUD_ID`,`SFLOW_PLCY_MSTR_ID`,`SALLW_APP_MSTR_ID`)
);

DROP TABLE IF EXISTS `TB_FLOW_PLCY_ALLW_USER`;
CREATE TABLE `TB_FLOW_PLCY_ALLW_USER` (
  `IFPAUSER_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SFLOW_PLCY_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SUSER_TYPE_CD` varchar(255) NOT NULL,
  `SALLW_USER_ID` varchar(255) NOT NULL,
  `SALLW_USER_GRUP_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IFPAUSER_NO`),
  KEY `IDX_FLOW_PLCY_ALLW_USER_001` (`SCLUD_ID`,`SALLW_USER_ID`,`SALLW_USER_GRUP_ID`),
  KEY `IDX_FLOW_PLCY_ALLW_USER_002` (`SCLUD_ID`,`SUSER_TYPE_CD`,`SALLW_USER_GRUP_ID`,`SFLOW_PLCY_MSTR_ID`)
);

DROP TABLE IF EXISTS `TB_FLOW_PLCY_MSTR`;
CREATE TABLE `TB_FLOW_PLCY_MSTR` (
  `SFPMSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SFLOW_PLCY_NM` varchar(255) NOT NULL,
  `STRSP_PRTC_CD` varchar(255) NOT NULL,
  `SFLOW_PLCY_CD` varchar(255) NOT NULL,
  `SDEST_NWTK_IP_TYPE_CD` varchar(255) NOT NULL,
  `SDEST_NTWK_DMAN_ARR` varchar(1000) NOT NULL,
  `SDEST_NTWK_IP_ARR` text NOT NULL,
  `SDEST_NTWK_STRT_IP` varchar(255) NOT NULL,
  `SDEST_NTWK_END_IP` varchar(255) NOT NULL,
  `SDEST_NWTK_PORT_TYPE_CD` varchar(255) NOT NULL,
  `SDEST_NTWK_PORT_ARR` varchar(1000) NOT NULL,
  `IDEST_NTWK_STRT_PORT` bigint(20) NOT NULL,
  `IDEST_NTWK_END_PORT` bigint(20) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SRSTR_RESN` varchar(255) NOT NULL,
  `SUSE_STRT_DT` varchar(255) NOT NULL,
  `SUSE_END_DT` varchar(255) NOT NULL,
  `IUSE_STRT_MS` bigint(20) NOT NULL,
  `IUSE_END_MS` bigint(20) NOT NULL,
  `SDESC` mediumtext NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  `SDEST_NTWK_DMAN_SYNC_TS` bigint(20) NOT NULL,
  `SDLTD_YN` varchar(255) NOT NULL,
  `SDLTD_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SFPMSTR_ID`),
  KEY `IDX_FLOW_PLCY_MSTR_001` (`SCLUD_ID`,`SSTAT_CD`,`STRSP_PRTC_CD`,`SDLTD_YN`),
  KEY `IDX_FLOW_PLCY_MSTR_002` (`SCLUD_ID`,`SSTAT_CD`,`SDLTD_YN`),
  KEY `IDX_FLOW_PLCY_MSTR_003` (`SCLUD_ID`,`SFPMSTR_ID`)
);

DROP TABLE IF EXISTS `TB_GNRL_APP`;
CREATE TABLE `TB_GNRL_APP` (
  `SGAPP_ID` varchar(255) NOT NULL,
  `SAPP_MSTR_ID` varchar(255) NOT NULL,
  `SGNRL_APP_GRUP_ID` varchar(255) NOT NULL,
  `SPROC_NM` varchar(255) NOT NULL,
  `SISPT_CNDT_JSON` mediumtext NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SGAPP_ID`),
  KEY `IDX_GNRL_APP_001` (`SAPP_MSTR_ID`),
  KEY `IDX_GNRL_APP_002` (`SPROC_NM`,`SSTAT_CD`)
);

DROP TABLE IF EXISTS `TB_GNRL_APP_GRUP`;
CREATE TABLE `TB_GNRL_APP_GRUP` (
  `SGAGRUP_ID` varchar(255) NOT NULL,
  `SREF_GNRL_APP_GRUP_ID` varchar(255) NOT NULL,
  `SGRUP_NM` varchar(255) NOT NULL,
  `SGRUP_FULL_NM` varchar(255) NOT NULL,
  `IGRUP_LV` bigint(20) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SGAGRUP_ID`)
);

DROP TABLE IF EXISTS `TB_LOGN_FAIL_INFO`;
CREATE TABLE `TB_LOGN_FAIL_INFO` (
  `ILFINFO_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `STYPE` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `ILOGN_RTRY_CNT` bigint(20) NOT NULL,
  `ILOGN_RSTR_EXPR_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`ILFINFO_NO`),
  KEY `IDX_LOGN_FAIL_INFO_01` (`STYPE`,`SLOGN_ID`)
);

DROP TABLE IF EXISTS `TB_MDTR_EXEC_APP`;
CREATE TABLE `TB_MDTR_EXEC_APP` (
  `IMEAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SCMPR_CD` varchar(255) NOT NULL,
  `SLOCA_ARR` varchar(4000) NOT NULL,
  `SEXEC_CMD` varchar(500) NOT NULL,
  `SDNLD_URL` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IMEAPP_NO`)
);

DROP TABLE IF EXISTS `TB_MDTR_INST_APP`;
CREATE TABLE `TB_MDTR_INST_APP` (
  `IMIIAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SCMPR_CD` varchar(255) NOT NULL,
  `SLOCA_ARR` varchar(4000) NOT NULL,
  `SPBLS_NM` varchar(255) NOT NULL,
  `SDNLD_URL` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IMIIAPP_NO`)
);

DROP TABLE IF EXISTS `TB_MDTR_PLTF_PTCH`;
CREATE TABLE `TB_MDTR_PLTF_PTCH` (
  `IMPPTCH_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_VRSN_ID` varchar(255) NOT NULL DEFAULT '',
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPLTF_VRSN` varchar(255) NOT NULL,
  `SPTCH_ID` varchar(255) NOT NULL,
  `SPTCH_NM` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IMPPTCH_NO`)
);

DROP TABLE IF EXISTS `TB_MENU`;
CREATE TABLE `TB_MENU` (
  `SMENU_ID` varchar(255) NOT NULL,
  `SREF_MENU_ID` varchar(255) NOT NULL,
  `SMENU_NM` varchar(255) NOT NULL,
  `SURL` varchar(255) NOT NULL,
  `SDESC` varchar(1000) NOT NULL,
  `ISEQ` bigint(20) NOT NULL,
  PRIMARY KEY (`SMENU_ID`)
);

DROP TABLE IF EXISTS `TB_MFA_TYPE`;
CREATE TABLE `TB_MFA_TYPE` (
  `IMFAT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SMFA_TYPE_CD` varchar(255) NOT NULL,
  `SMFA_TYPE_CD_ARR` varchar(255) NOT NULL DEFAULT '',
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IMFAT_NO`)
);

DROP TABLE IF EXISTS `TB_MSG`;
CREATE TABLE `TB_MSG` (
  `SMSG_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCATE_CD` varchar(255) NOT NULL,
  `SCATE_MSG` varchar(1000) NOT NULL,
  `SCATE_LV_CD` varchar(255) NOT NULL,
  `SMSG_CD` varchar(255) NOT NULL,
  `SEVDC_MSG` varchar(1000) NOT NULL,
  `SVRTL_MSG_KR` varchar(1000) NOT NULL,
  `SVRTL_MSG_EN` varchar(1000) NOT NULL,
  `SVRTL_MSG_JP` varchar(1000) NOT NULL,
  `SVRTL_MSG_CN` varchar(1000) NOT NULL,
  `SHELP_URL` varchar(255) NOT NULL,
  `SHELP_CNTC_INFO` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SMSG_ID`),
  KEY `IDX_MSG_02` (`SCLUD_ID`,`SMSG_CD`)
);

DROP TABLE IF EXISTS `TB_NATV_APP`;
CREATE TABLE `TB_NATV_APP` (
  `SNAPP_ID` varchar(255) NOT NULL,
  `SAPP_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SPROC_NM` varchar(255) NOT NULL,
  `SISPT_CNDT_JSON` mediumtext NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SRSTR_RESN` varchar(500) NOT NULL,
  `SCNCT_DT` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SNAPP_ID`),
  KEY `IDX_NATV_APP_001` (`SCLUD_ID`,`SAPP_MSTR_ID`),
  KEY `IDX_NATV_APP_002` (`SCLUD_ID`,`SPROC_NM`,`SSTAT_CD`)
);

DROP TABLE IF EXISTS `TB_NOT_ALLW_EXEC_APP`;
CREATE TABLE `TB_NOT_ALLW_EXEC_APP` (
  `INAEAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SLOCA` varchar(4000) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`INAEAPP_NO`)
);

DROP TABLE IF EXISTS `TB_NOT_ALLW_INST_APP`;
CREATE TABLE `TB_NOT_ALLW_INST_APP` (
  `INAIAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SLOCA` varchar(4000) NOT NULL,
  `SPBLS_NM` varchar(255) NOT NULL,
  `SUNST_CMD` varchar(255) NOT NULL,
  `SNEED_UNST_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`INAIAPP_NO`)
);

DROP TABLE IF EXISTS `TB_NOT_ALLW_NTWK_LSTN_PORT`;
CREATE TABLE `TB_NOT_ALLW_NTWK_LSTN_PORT` (
  `INANLPORT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPORT_RNGE` varchar(255) NOT NULL,
  `SDESC` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`INANLPORT_NO`)
);

DROP TABLE IF EXISTS `TB_NOT_ALLW_PLTF_VRSN`;
CREATE TABLE `TB_NOT_ALLW_PLTF_VRSN` (
  `INAPVRSN_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPLTF_VRSN` varchar(255) NOT NULL,
  `SPRDT_NM` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`INAPVRSN_NO`)
);

DROP TABLE IF EXISTS `TB_OFFC_HOUR`;
CREATE TABLE `TB_OFFC_HOUR` (
  `IOHOUR_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SSTRT_HM` varchar(255) NOT NULL,
  `SEND_HM` varchar(255) NOT NULL,
  `SWKND_ACSS_ALLW_YN` varchar(255) NOT NULL DEFAULT '',
  `SHDAY_ACSS_ALLW_YN` varchar(255) NOT NULL DEFAULT '',
  `SOTHR_HDAY_ARRAY` longtext NOT NULL DEFAULT '',
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IOHOUR_NO`)
);

DROP TABLE IF EXISTS `TB_PLGE`;
CREATE TABLE `TB_PLGE` (
  `SPLGE_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SROOT_PLGE_ID` varchar(255) NOT NULL,
  `STITLE` varchar(255) NOT NULL,
  `SATTR1` varchar(255) NOT NULL,
  `SATTR2` varchar(255) NOT NULL,
  `SATTR3` varchar(255) NOT NULL,
  `SATTR4` varchar(255) NOT NULL,
  `SATTR5` varchar(255) NOT NULL,
  `SATTR6` varchar(255) NOT NULL,
  `SATTR7` varchar(255) NOT NULL,
  `SATTR8` varchar(255) NOT NULL,
  `SDESC` longtext NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SACTV_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SPLGE_ID`)
);

DROP TABLE IF EXISTS `TB_PLTF_VRSN`;
CREATE TABLE `TB_PLTF_VRSN` (
  `SPVRSN_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SPRDT_NM` varchar(255) NOT NULL,
  `SVRSN` varchar(255) NOT NULL,
  `SVRSN_DC` mediumtext NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SPVRSN_ID`)
);

DROP TABLE IF EXISTS `TB_PRMT`;
CREATE TABLE `TB_PRMT` (
  `SPRMT_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SPRMT_NM` varchar(255) NOT NULL,
  `SPRMT_TYPE_CD` varchar(255) NOT NULL,
  `SDPLY_TYPE_CD` varchar(255) NOT NULL,
  `SREGN_ID` varchar(255) NOT NULL DEFAULT '',
  `SPCXF_YN` varchar(255) NOT NULL DEFAULT 'N',
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`SPRMT_ID`)
);

DROP TABLE IF EXISTS `TB_REGN`;
CREATE TABLE `TB_REGN` (
  `SREGN_ID` varchar(255) NOT NULL,
  `SREGN_NM` varchar(255) NOT NULL,
  `ISORT` bigint(20) NOT NULL,
  `SDESC` varchar(4000) NOT NULL,
  PRIMARY KEY (`SREGN_ID`)
);

DROP TABLE IF EXISTS `TB_REGN_CNTR`;
CREATE TABLE `TB_REGN_CNTR` (
  `IREGN_CNTR_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SREGN_ID` varchar(255) NOT NULL,
  `SCNTR_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`IREGN_CNTR_NO`)
);

DROP TABLE IF EXISTS `TB_RISK_ANLY_OVRV`;
CREATE TABLE `TB_RISK_ANLY_OVRV` (
  `SRAOVRV_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STF_CD` varchar(255) NOT NULL,
  `ICTRL_FLOW_RQST_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_CRET_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_RJCT_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_DISC_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_DISC_NRML_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_DISC_ABNM_CNT` bigint(20) NOT NULL,
  `IBHVR_CTRL_DTCT_CNT` bigint(20) NOT NULL,
  `IBHVR_CTRL_RJCT_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_RQST_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_DISC_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_DISC_NRML_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_DISC_ABNM_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_RJCT_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_CRET_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_BLCK_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_ISOL_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_ISOL_RELS_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_RJCT_RISK_LV_1_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_RJCT_RISK_LV_2_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_RJCT_RISK_LV_3_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_RJCT_RISK_LV_1_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_RJCT_RISK_LV_2_CNT` bigint(20) NOT NULL,
  `IDATA_FLOW_RJCT_RISK_LV_3_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_DISC_RISK_LV_1_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_DISC_RISK_LV_2_CNT` bigint(20) NOT NULL,
  `ICTRL_FLOW_DISC_RISK_LV_3_CNT` bigint(20) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SRAOVRV_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_ANLY_OVRV_EVDC`;
CREATE TABLE `TB_RISK_ANLY_OVRV_EVDC` (
  `SRAOEVDC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SEVDC_ID` varchar(255) NOT NULL,
  `SRISK_ANLY_STAT_OVRV_ID` varchar(255) NOT NULL,
  `SEVDC_TYPE_CD` varchar(255) NOT NULL,
  `SRISK_LV_CD` varchar(255) NOT NULL,
  `STRGT_DC` varchar(255) NOT NULL,
  `SEVDC_DC` varchar(255) NOT NULL,
  `SEVDC_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SRAOEVDC_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_ANLY_OVRV_RESN`;
CREATE TABLE `TB_RISK_ANLY_OVRV_RESN` (
  `SRAORESN_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_ANLY_STAT_OVRV_ID` varchar(255) NOT NULL,
  `SRESN_TYPE_CD` varchar(255) NOT NULL,
  `SRISK_LV_CD` varchar(255) NOT NULL,
  `SRESN_DC` varchar(255) NOT NULL,
  `ISEQ` bigint(20) NOT NULL,
  `ICNT` bigint(20) NOT NULL,
  `IPRCT` bigint(20) NOT NULL,
  PRIMARY KEY (`SRAORESN_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_CTRL_APLY_ITEM`;
CREATE TABLE `TB_RISK_CTRL_APLY_ITEM` (
  `IRCAITEM_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_MSTR_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_ITEM_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_JSON` mediumtext NOT NULL,
  `SAPLY_PLTF_CD_ARR` varchar(255) NOT NULL,
  `SREPT_YN` varchar(1) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IRCAITEM_NO`),
  KEY `IDX_RISK_CTRL_APLY_ITEM_01` (`SRISK_CTRL_MSTR_ID`, `SRISK_CTRL_ITEM_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_CTRL_APLY_ITEM_CNDT`;
CREATE TABLE `TB_RISK_CTRL_APLY_ITEM_CNDT` (
  `IRCAICNDT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `IRISK_CTRL_APLY_ITEM_NO` bigint(20) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IRCAICNDT_NO`)
);

DROP TABLE IF EXISTS `TB_RISK_CTRL_APLY_USER`;
CREATE TABLE `TB_RISK_CTRL_APLY_USER` (
  `IRCAUSER_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SRISK_CTRL_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SUSER_TYPE_CD` varchar(255) NOT NULL,
  `SAPLY_USER_ID` varchar(255) NOT NULL,
  `SAPLY_USER_GRUP_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IRCAUSER_NO`),
  KEY `IDX_RISK_CTRL_APLY_USER_01` (`SUSER_TYPE_CD`,`SAPLY_USER_ID`),
  KEY `IDX_RISK_CTRL_APLY_USER_02` (`SUSER_TYPE_CD`,`SAPLY_USER_GRUP_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_CTRL_CNDT_MSTR`;
CREATE TABLE `TB_RISK_CTRL_CNDT_MSTR` (
  `SRCCMSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCNDT_CD` varchar(255) NOT NULL,
  `SCNDT_NM` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SRCCMSTR_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_CTRL_EXCL_TRGT`;
CREATE TABLE `TB_RISK_CTRL_EXCL_TRGT` (
  `IRCETRGT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SRISK_CTRL_MSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SUSER_TYPE_CD` varchar(255) NOT NULL,
  `SEXCL_USER_ID` varchar(255) NOT NULL,
  `SEXCL_USER_GRUP_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IRCETRGT_NO`),
  KEY `IDX_RISK_CTRL_EXCL_TRGT_01` (`SUSER_TYPE_CD`,`SEXCL_USER_ID`),
  KEY `IDX_RISK_CTRL_EXCL_TRGT_02` (`SUSER_TYPE_CD`,`SEXCL_USER_GRUP_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_CTRL_ITEM`;
CREATE TABLE `TB_RISK_CTRL_ITEM` (
  `SRCITEM_ID` varchar(255) NOT NULL,
  `SITEM_NM` varchar(255) NOT NULL,
  `SITEM_DC` mediumtext NOT NULL,
  `SITEM_NM_EN` VARCHAR(255) NOT NULL,
  `SITEM_DC_EN` MEDIUMTEXT NOT NULL,
  `SITEM_NM_JP` VARCHAR(255) NOT NULL,
  `SITEM_DC_JP` MEDIUMTEXT NOT NULL,
  `SRISK_CTRL_CD` varchar(255) NOT NULL,
  `SRISK_LV_CD` varchar(255) NOT NULL,
  `SDFLT_CTRL_CNDT_JSON` mediumtext NOT NULL,
  `SAPLY_ACT_CD_ARR` varchar(500) NOT NULL,
  `SAPLY_PLTF_CD_ARR` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SRCITEM_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_CTRL_MSTR`;
CREATE TABLE `TB_RISK_CTRL_MSTR` (
  `SRCMSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_NM` varchar(255) NOT NULL,
  `SRISK_CTRL_CD` varchar(255) NOT NULL,
  `SAPLY_ALL_ROUT_YN` varchar(255) NOT NULL,
  `SAPLY_ALL_USER_YN` varchar(255) NOT NULL,
  `SPLTF_CD_ARR` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  `SDLTD_YN` varchar(255) NOT NULL,
  `SDLTD_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SRCMSTR_ID`),
  KEY `IDX_RISK_CTRL_MSTR_01` (`SSTAT_CD`),
  KEY `IDX_RISK_CTRL_MSTR_002` (`SSTAT_CD`, `SAPLY_ALL_ROUT_YN`, `SAPLY_ALL_USER_YN`, `SCLUD_ID`)
);

DROP TABLE IF EXISTS `TB_RISK_DSBD`;
CREATE TABLE `TB_RISK_DSBD` (
  `SRDSBD_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_ANLY_TF_CD` varchar(255) NOT NULL,
  `IEVDC_STBY_CNT` bigint(20) NOT NULL,
  `ICLUD_APRV_STBY_CNT` bigint(20) NOT NULL,
  `IEVDC_CNT` bigint(20) NOT NULL,
  `IEVNT_LOG_CNT` bigint(20) NOT NULL,
  `ICLUD_USER_CNT` bigint(20) NOT NULL,
  `ICNCT_USER_CNT` bigint(20) NOT NULL,
  `ICLUD_DEVC_CNT` bigint(20) NOT NULL,
  `ICNCT_DEVC_CNT` bigint(20) NOT NULL,
  `IFLOW_PLCY_CNT` bigint(20) NOT NULL,
  `IROUT_PLCY_CNT` bigint(20) NOT NULL,
  `ISENT_TRFC_PER_MB` bigint(20) NOT NULL,
  `IACCU_SENT_TRFC_MB` bigint(20) NOT NULL,
  `IRECV_TRFC_PER_MB` bigint(20) NOT NULL,
  `IACCU_RECV_TRFC_MB` bigint(20) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SRDSBD_ID`)
);

DROP TABLE IF EXISTS `TB_ROUT_PLCY`;
CREATE TABLE `TB_ROUT_PLCY` (
  `SRPLCY_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SROUT_NM` varchar(255) NOT NULL,
  `SROUT_CD` varchar(255) NOT NULL,
  `SDEVC_CTRL_CD` varchar(255) NOT NULL,
  `SSRC_PRMT_ID` varchar(255) NOT NULL,
  `SITMD_PRMT_ID` varchar(255) NOT NULL,
  `SDEST_PRMT_ID` varchar(255) NOT NULL,
  `SFLOW_ROUT_CIDR_ARR` varchar(4000) NOT NULL,
  `SFLOW_PTCL_CD` varchar(255) NOT NULL,
  `SFLOW_DRVR_LV_ENCR_ALGO_CD` varchar(255) NOT NULL,
  `SROUT_DTCT_TYPE_CD` varchar(255) NOT NULL,
  `SROUT_DTCT_CIDR_ARR` varchar(255) NOT NULL,
  `SUSE_PRVT_DNS_YN` varchar(255) NOT NULL,
  `SPRVT_DNS_PRMR_IP` varchar(255) NOT NULL,
  `SPRVT_DNS_SCND_IP` varchar(255) NOT NULL,
  `SAUTH_AFTR_CNCT_YN` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  `SDLTD_YN` varchar(255) NOT NULL,
  `SDLTD_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SRPLCY_ID`)
);

DROP TABLE IF EXISTS `TB_ROUT_PLCY_TRGT`;
CREATE TABLE `TB_ROUT_PLCY_TRGT` (
  `IRPTRGT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SROUT_PLCY_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STRGT_CD` varchar(255) NOT NULL,
  `STRGT_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IRPTRGT_NO`),
  KEY `IDX_ROUT_PLCY_TRGT_001` (`SCLUD_ID`,`STRGT_ID`)
);

DROP TABLE IF EXISTS `TB_SCRT_MFA_SESN`;
CREATE TABLE `TB_SCRT_MFA_SESN` (
  `SSMSESN_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SAUTH_TYPE_CD` varchar(255) NOT NULL,
  `SSESN_TYPE_CD` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SCORE_DATA_FLOW_ID` varchar(255) NOT NULL,
  `SOTP_KEY` varchar(255) NOT NULL,
  `SOTP_NO` varchar(255) NOT NULL,
  `SEMAL_ADDR` varchar(1000) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  `IEXPR_TS` bigint(20) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  PRIMARY KEY (`SSMSESN_ID`),
  KEY `IDX_SCRT_MFA_SESN_001` (`SCORE_CTRL_FLOW_MSTR_ID`),
  KEY `IDX_SCRT_MFA_SESN_002` (`SCORE_DATA_FLOW_ID`),
  KEY `IDX_SCRT_MFA_SESN_003` (`SSESN_TYPE_CD`)
);

DROP TABLE IF EXISTS `TB_SMTP`;
CREATE TABLE `TB_SMTP` (
  `ISMTP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SHOST` varchar(255) NOT NULL,
  `IPORT` bigint(20) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SPWD` varchar(1000) NOT NULL,
  `SFROM` text NOT NULL,
  `SAUTH_YN` varchar(255) NOT NULL,
  `SSSL_YN` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ISMTP_NO`)
);

DROP TABLE IF EXISTS `TB_SYNC_TUNL_USER_Q`;
CREATE TABLE `TB_SYNC_TUNL_USER_Q` (
  `ISTUQ_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCGW_ID` varchar(255) NOT NULL,
  `SCGUNIT_ID` varchar(255) NOT NULL,
  `SGW_API_SRVR_IP` varchar(255) NOT NULL,
  `SGW_API_SRVR_PORT` bigint(20) NOT NULL,
  `SHTTPS_YN` varchar(255) NOT NULL,
  `SSYNC_STAT_CD` varchar(255) NOT NULL,
  `SDATA` longtext NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SSYNC_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ISTUQ_NO`)
);

DROP TABLE IF EXISTS `TB_SYS_LOG`;
CREATE TABLE `TB_SYS_LOG` (
  `ISLOG_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SINFR_TYPE_CD` varchar(50) NOT NULL,
  `SINFR_TYPE_NM` varchar(50) NOT NULL,
  `SSRVR_INFO` varchar(255) NOT NULL,
  `STYPE_CD` varchar(255) NOT NULL,
  `STYPE_NM` varchar(255) NOT NULL,
  `SREF_ID` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `SSTAT_NM` varchar(255) NOT NULL,
  `SDESC` longtext NOT NULL,
  `SSTT_DT` varchar(255) NOT NULL,
  `SEND_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ISLOG_NO`),
  KEY `IDX_SYS_LOG_01` (`SSTT_DT`,`SEND_DT`)
);

DROP TABLE IF EXISTS `TB_TASK_Q`;
CREATE TABLE `TB_TASK_Q` (
  `ITQ_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `STASK_CD` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `STRGT_IP` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`ITQ_NO`)
);

DROP TABLE IF EXISTS `TB_ASST_KOHYOUNG`;
CREATE TABLE `TB_ASST_KOHYOUNG` (
    `SLOGN_ID` varchar(255) NOT NULL,
    `SATTR1` varchar(500) NOT NULL,
    `SATTR2` varchar(500) NOT NULL,
    `SATTR3` varchar(500) NOT NULL,
    `SATTR4` varchar(500) NOT NULL,
    `SATTR5` varchar(500) NOT NULL,
    `SATTR6` varchar(500) NOT NULL,
    `SATTR7` varchar(500) NOT NULL,
    PRIMARY KEY (`SLOGN_ID`)
);

DROP TABLE IF EXISTS `TB_USER_MSTR`;
CREATE TABLE `TB_USER_MSTR` (
  `SUMSTR_ID` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SEMAL_ADDR` varchar(255) NOT NULL,
  `SLOGN_PW` varchar(255) NOT NULL,
  `SSMPL_LOGN_PW` varchar(255) NOT NULL,
  `SSMPL_LOGN_PW_SALT` varchar(255) NOT NULL,
  `SFIDO` varchar(255) NOT NULL,
  `SFIDO_SALT` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SCELL_PHON_NO` varchar(255) NOT NULL,
  `SLAST_LOGN_DT` varchar(255) NOT NULL,
  `SLAST_LOGN_IP` varchar(255) NOT NULL,
  `SLOGN_RTRY_CNT` bigint(20) NOT NULL,
  `ILOGN_RSTR_EXPR_TS` bigint(20) NOT NULL,
  `ILAST_CHNG_LOGN_PW_TS` bigint(20) NOT NULL,
  `SAWAY_YN` varchar(255) NOT NULL,
  `SRSTR_RESN` varchar(255) NOT NULL,
  `SUSE_STRT_DT` varchar(255) NOT NULL,
  `SUSE_END_DT` varchar(255) NOT NULL,
  `SSYNC_USER_ID` varchar(255) NOT NULL,
  `SSTTC_IP_ARR` varchar(255) NOT NULL,
  `SSTTC_IP_SSL_VPN` varchar(255) NOT NULL DEFAULT '',
  `SSTAT_CD` varchar(255) NOT NULL,
  `SSALT` varchar(255) NOT NULL,
  `SBRTH` varchar(255) NOT NULL,
  `SUSER_FLAG` varchar(255) NOT NULL,
  `SUNQ_ID` varchar(255) NOT NULL,
  `STOTP_KEY` varchar(255) NOT NULL DEFAULT '',
  `SRGST_DT` varchar(255) NOT NULL,
  `SWTDR_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`SUMSTR_ID`),
  UNIQUE KEY `SLOGN_ID` (`SLOGN_ID`)
);

DROP TABLE IF EXISTS `TB_CLUD_USER_SYNC_LDAP`;
CREATE TABLE `TB_CLUD_USER_SYNC_LDAP` (
  `SCUSLDAP_ID` varchar(255) NOT NULL,
  `SCLUD_USER_SYNC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SLDAP_TYPE_CD` varchar(255) NOT NULL,
  `SLDAP_IP` varchar(255) NOT NULL,
  `SLDAP_PORT` varchar(255) NOT NULL,
  `SLDAP_SSL_YN` varchar(255) NOT NULL,
  `SLDAP_USER_ID` varchar(255) NOT NULL,
  `SLDAP_USER_PW` varchar(255) NOT NULL,
  `SLDAP_BASE_DN` varchar(255) NOT NULL,
  `SLDAP_ORG_DN` varchar(255) NOT NULL,
  `SLDAP_AUTH_TYPE` varchar(255) NOT NULL,
  `SLDAP_PER_SIZE` varchar(255) NOT NULL,
  `SSYNC_DLTD_USER_YN` varchar(255) NOT NULL,
  `SSYNC_UPDT_USER_YN` varchar(255) NOT NULL,
  `SSYNC_FRCD_UPDT_USER_YN` varchar(255) NOT NULL,
  `SUSER_SYNC_OBJECT_CLASS` varchar(255) NOT NULL,
  `SUSER_DN_ATTR` varchar(255) NOT NULL,
  `SUSER_LOGN_ID_ATTR` varchar(255) NOT NULL,
  `SUSER_NM_ATTR` varchar(255) NOT NULL,
  `SUSER_EMAL_ATTR` varchar(255) NOT NULL,
  `SUSER_CELL_PHON_NO_ATTR` varchar(255) NOT NULL,
  `SREL_USER_GRUP_ID_ATTR` varchar(255) NOT NULL,
  `SUSER_PW_ATTR` varchar(255) NOT NULL,
  `SUSER_PW_CHNG_DT_SYNC_CODE` varchar(255) NOT NULL DEFAULT '',
  `SUSER_INIT_STAT_CD` varchar(255) NOT NULL DEFAULT 'C_USABLE',
  `SUSER_GRUP_SYNC_YN` varchar(255) NOT NULL,
  `SSYNC_DLTD_USER_GRUP_YN` varchar(255) NOT NULL,
  `SSYNC_UPDT_USER_GRUP_YN` varchar(255) NOT NULL,
  `SUSER_GRUP_SYNC_OBJECT_CLASS` varchar(255) NOT NULL,
  `SUSER_GRUP_DN_ATTR` varchar(255) NOT NULL,
  `SUSER_GRUP_ID_ATTR` varchar(255) NOT NULL,
  `SREF_USER_GRUP_ID_ATTR` varchar(255) NOT NULL,
  `SUSER_GRUP_NM_ATTR` varchar(255) NOT NULL,
  `SUSER_GRUP_SORT_ATTR` varchar(255) NOT NULL,
  `SUSER_GRUP_ROOT_ID` varchar(255) NOT NULL,
  `SUSER_GRUP_ROOT_SYNC_ID` varchar(255) NOT NULL,
  `SSALT` varchar(255) NOT NULL DEFAULT '',
  `SDATA_ENCR_KEY` text NOT NULL DEFAULT '',
  `SDATA_ENCR_IV` text NOT NULL DEFAULT '',
  `SEXEC_DT` varchar(255) NOT NULL,
  `SEXEC_STAT_CD` varchar(255) NOT NULL,
  `SEXEC_LOG` mediumtext NOT NULL,
  PRIMARY KEY (`SCUSLDAP_ID`)
);

DROP TABLE IF EXISTS `TB_VGW_EXIT_WITH_APP`;
CREATE TABLE `TB_VGW_EXIT_WITH_APP` (
  `IVGWEWAPP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SPLTF_CD` varchar(255) NOT NULL,
  `SAPP_NM` varchar(255) NOT NULL,
  `SLOCA_ARR` varchar(500) NOT NULL,
  `SEXEC_CMD` varchar(500) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  `SUPDT_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`IVGWEWAPP_NO`)
);

DROP TABLE IF EXISTS `TB_USER_NOTI_CHCK`;
CREATE TABLE `TB_USER_NOTI_CHCK` (
  `SLOGN_ID` varchar(255) NOT NULL,
  `SLAST_NOTI_CHCK_DATE` varchar(255) DEFAULT NULL,
  `SNOTI_CHCK` varchar(10) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`SLOGN_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_PRTC_LOGC_PFMC`;
CREATE TABLE `TB_CORE_INFR_PRTC_LOGC_PFMC` (
  `SCIPLPFMC_ID` VARCHAR(255) NOT NULL,
  `SCORE_INFR_PRTC_PFMC_ID` VARCHAR(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` VARCHAR(255) NOT NULL,
  `SPRTC_CD` VARCHAR(255) NOT NULL,
  `SLOGC_CD` VARCHAR(255) NOT NULL,
  `ISEQ` BIGINT(20) NOT NULL,
  `IAVG_PRCS_TIME` BIGINT(20) NOT NULL,
  `SINST_DT` VARCHAR(255) NOT NULL,
  `SUPDT_DT` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SCIPLPFMC_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_INFR_PRTC_PFMC`;
CREATE TABLE `TB_CORE_INFR_PRTC_PFMC` (
  `SCIPPFMC_ID` VARCHAR(255) NOT NULL,
  `SCORE_INFR_MSTR_ID` VARCHAR(255) NOT NULL,
  `SPRTC_CD` VARCHAR(255) NOT NULL,
  `IAVG_PRCS_TIME` BIGINT(20) NOT NULL,
  `IEXEC_CNT` BIGINT(20) NOT NULL,
  `IFAIL_CNT` BIGINT(20) NOT NULL,
  `SINST_DT` VARCHAR(255) NOT NULL,
  `SUPDT_DT` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SCIPPFMC_ID`)
);

DROP TABLE IF EXISTS `TB_SYSLOG`;
CREATE TABLE `TB_SYSLOG` (
  `SSYSLOG_ID` VARCHAR(255) NOT NULL,
  `STRSP_PRTC_CD` VARCHAR(255) NOT NULL,
  `SADDR` VARCHAR(255) NOT NULL,
  `IPORT` BIGINT(20) NOT NULL,
  `SFNC` VARCHAR(255) NOT NULL,
  `SFRMT` VARCHAR(255) NOT NULL,
  `SSTAT_CD` VARCHAR(255) NOT NULL,
  `SDSCR` VARCHAR(255) NOT NULL,
  `IINST_TS` BIGINT(20) NOT NULL,
  `IUPDT_TS` BIGINT(20) NOT NULL,
  PRIMARY KEY (`SSYSLOG_ID`)
);

DROP TABLE IF EXISTS TB_SNMP;
CREATE TABLE `TB_SNMP` (
  `SSNMP_ID` VARCHAR(255) NOT NULL,
  `SVRSN_CD` VARCHAR(255) NOT NULL,
  `SCMNT_NM` VARCHAR(255) NOT NULL,
  `SUSER_NM` VARCHAR(255) NOT NULL,
  `SCRT_CD` VARCHAR(255) NOT NULL,
  `SUSER_AUTH_SCRT_CD` VARCHAR(255) NOT NULL,
  `SUSER_AUTH_PWD` VARCHAR(255) NOT NULL,
  `SMSG_ENCR_SCRT_CD` VARCHAR(255) NOT NULL,
  `SMSG_ENCR_PWD` VARCHAR(255) NOT NULL,
  `STRAP_ADDR` VARCHAR(255) NOT NULL,
  `ITRAP_PORT` BIGINT(20) NOT NULL,
  `STRAP_STAT_CD` VARCHAR(255) NOT NULL,
  `SDSCR` VARCHAR(255) NOT NULL,
  `SKEY_ENCR_PRVT_KEY` TEXT NOT NULL,
  `SDATA_ENCR_KEY` TEXT NOT NULL,
  `SDATA_ENCR_IV` TEXT NOT NULL,
  `SSTAT_CD` VARCHAR(255) NOT NULL,
  `IINST_TS` BIGINT(20) NOT NULL,
  `IUPDT_TS` BIGINT(20) NOT NULL,
  PRIMARY KEY (`SSNMP_ID`)
);

DROP TABLE IF EXISTS `TB_USER_MST_TEMP`;
CREATE TABLE `TB_USER_MST_TEMP` (
  `SUMTEMP_ID` varchar(255) NOT NULL,
  `SCORE_CTRL_FLOW_MSTR_ID` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SLOGN_PW` varchar(255) NOT NULL,
  `SSALT` varchar(255) NOT NULL,
  `SUSER_NM` varchar(255) NOT NULL,
  `SCELL_PHON_NO` varchar(255) NOT NULL,
  `SSMS_OTP_CNFM_YN` varchar(255) NOT NULL,
  PRIMARY KEY (`SUMTEMP_ID`),
  UNIQUE KEY `SLOGN_ID` (`SLOGN_ID`)
);

DROP TABLE IF EXISTS `TB_PLCY_RULE_LOG`;
CREATE TABLE `TB_PLCY_RULE_LOG` (
  `SPRLOG_ID` varchar(255) NOT NULL,
  `SEVDC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_ITEM_ID` varchar(255) NOT NULL,
  `SPLCY_RULE_CD` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SDEVC_HOST_NM` varchar(255) NOT NULL,
  `SDEVC_MODL_NM` varchar(255) NOT NULL,
  `SDEVC_PLTF_CD` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`SPRLOG_ID`)
);

DROP TABLE IF EXISTS `TB_FLOW_RULE_LOG`;
CREATE TABLE `TB_FLOW_RULE_LOG` (
  `SFRLOG_ID` varchar(255) NOT NULL,
  `SEVDC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCTRL_FLOW_EXCP_CD` varchar(255) NOT NULL,
  `SFLOW_RULE_CD` varchar(255) NOT NULL,
  `SLOGN_ID` varchar(255) NOT NULL,
  `SDATA_FLOW_DEST_URL` varchar(255) NOT NULL,
  `SDATA_FLOW_APP_ID` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`SFRLOG_ID`)
);

DROP TABLE IF EXISTS `TB_CORE_GW_TRST_DEST_NEWK`;
CREATE TABLE `TB_CORE_GW_TRST_DEST_NEWK` (
  `ICGTDNEWK_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SCORE_GW_ID` varchar(255) NOT NULL,
  `STRSP_PRTC_CD` varchar(255) NOT NULL,
  `SALLOW_IP` varchar(255) NOT NULL,
  `IALLOW_PORT` varchar(255) NOT NULL,
  `IINST_DT` bigint(20) NOT NULL,
  PRIMARY KEY (`ICGTDNEWK_NO`)
);

DROP TABLE IF EXISTS `TB_VPN_STTC_IP_GRUP_MSTR`;
CREATE TABLE `TB_VPN_STTC_IP_GRUP_MSTR` (
  `SVSIGMSTR_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SVIP_CIDR` varchar(255) NOT NULL,
  `SSTRT_IP` varchar(255) NOT NULL,
  `SEND_IP` varchar(255) NOT NULL,
  `IALCT_MAX_CNT` bigint(20) NOT NULL,
  `IEXPR_HOUR` bigint(20) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  `IUPDT_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`SVSIGMSTR_ID`)
);

DROP TABLE IF EXISTS `TB_VPN_STTC_IP_CLUD_USER_GRUP`;
CREATE TABLE `TB_VPN_STTC_IP_CLUD_USER_GRUP` (
  `IVSICUGRUP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SVPN_STTC_IP_GRUP_MSTR_ID` varchar(255) NOT NULL,
  `SUSER_TYPE_CD` varchar(255) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SCLUD_USER_GRUP_ID` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IVSICUGRUP_NO`)
);

DROP TABLE IF EXISTS `TB_VPN_STTC_IP`;
CREATE TABLE `TB_VPN_STTC_IP` (
  `IVSIP_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SVPN_STTC_IP_GRUP_MSTR_ID` varchar(255) NOT NULL,
  `SVIP` varchar(255) NOT NULL,
  `IIP_NMRC` bigint(20) NOT NULL,
  `SCLUD_USER_ID` varchar(255) NOT NULL,
  `SNODE_ID` varchar(255) NOT NULL,
  `IDISC_TS` bigint(20) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  `IUPDT_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`IVSIP_NO`)
);

DROP TABLE IF EXISTS `TB_NTC_APLY_TRGT`;
CREATE TABLE `TB_NTC_APLY_TRGT` (
  `INATRGT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SNTC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SUSER_TYPE_CD` varchar(255) NOT NULL,
  `SAPLY_USER_ID` varchar(255) NOT NULL,
  `SAPLY_USER_GRUP_ID` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`INATRGT_NO`),
  KEY `IDX_NTC_APLY_TRGT_01` (`SUSER_TYPE_CD`,`SAPLY_USER_ID`),
  KEY `IDX_NTC_APLY_TRGT_02` (`SUSER_TYPE_CD`,`SAPLY_USER_GRUP_ID`)
);

DROP TABLE IF EXISTS `TB_NTC_EXCL_TRGT`;
CREATE TABLE `TB_NTC_EXCL_TRGT` (
  `INETRGT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SNTC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SUSER_TYPE_CD` varchar(255) NOT NULL,
  `SEXCL_USER_ID` varchar(255) NOT NULL,
  `SEXCL_USER_GRUP_ID` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`INETRGT_NO`),
  KEY `IDX_NTC_EXCL_TRGT_01` (`SUSER_TYPE_CD`,`SEXCL_USER_ID`),
  KEY `IDX_NTC_EXCL_TRGT_02` (`SUSER_TYPE_CD`,`SEXCL_USER_GRUP_ID`)
);

DROP TABLE IF EXISTS `TB_NTC`;
CREATE TABLE `TB_NTC` (
  `SNTC_ID` varchar(255) NOT NULL,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SNTC_NM` varchar(255) NOT NULL,
  `SCNTS` text NOT NULL,
  `SSHW_USE_YN` varchar(255) NOT NULL,
  `SAPLY_ALL_USER_YN` varchar(255) NOT NULL,
  `SUSE_STRT_DT` varchar(255) NOT NULL,
  `SUSE_END_DT` varchar(255) NOT NULL,
  `SSTAT_CD` varchar(255) NOT NULL,
  `IINST_TS` bigint(20) NOT NULL,
  `IUPDT_TS` bigint(20) NOT NULL,
  PRIMARY KEY (`SNTC_ID`)
);

DROP TABLE IF EXISTS `TB_NOT_ALLW_WIFI_ROUT`;
CREATE TABLE `TB_NOT_ALLW_WIFI_ROUT` (
  `INAWROUT_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `SCLUD_ID` varchar(255) NOT NULL,
  `SRISK_CTRL_CNDT_MSTR_ID` varchar(255) NOT NULL,
  `SWIFI_ROUT_ID` varchar(255) NOT NULL,
  `SINST_DT` varchar(255) NOT NULL,
  PRIMARY KEY (`INAWROUT_NO`)
);

CREATE OR REPLACE VIEW `VW_TREE_CLUD_USER_GRUP`
AS
    with recursive TR_CLUD_USER_GRUP
        as (select `G`.`SCUGRUP_ID` AS `RCUGRUP_ID`,
                    `G`.`SGRUP_NM` AS `RGRUP_NM`,
                    `G`.`SCUGRUP_ID` AS `CUGRUP_ID`,
                    `G`.`SREF_USER_GRUP_ID` AS `REF_USER_GRUP_ID`,
                    `G`.`SGRUP_NM` AS `GRUP_NM`,
                    `G`.`SCLUD_ID` AS `CLUD_ID`,
                    1 AS `LVL`
            from `TB_CLUD_USER_GRUP` `G`
            where `G`.`SCUGRUP_ID` <> `G`.`SREF_USER_GRUP_ID`
            union
            select `TG`.`RCUGRUP_ID` AS `RCUGRUP_ID`,
                    `TG`.`RGRUP_NM` AS `RGRUP_NM`,
                    `G`.`SCUGRUP_ID` AS `SCUGRUP_ID`,
                    `G`.`SREF_USER_GRUP_ID` AS `SREF_USER_GRUP_ID`,
                    `G`.`SGRUP_NM` AS `SGRUP_NM`,
                    `G`.`SCLUD_ID` AS `SCLUD_ID`,
                    `TG`.`LVL` + 1 AS `LVL+1`
            from (`TB_CLUD_USER_GRUP` `G` join `TR_CLUD_USER_GRUP` `TG`)
            where `TG`.`CUGRUP_ID` = `G`.`SREF_USER_GRUP_ID`
            and `TG`.`CLUD_ID` = `G`.`SCLUD_ID`
            and `G`.`SCUGRUP_ID` <> `G`.`SREF_USER_GRUP_ID`
            )
select `A`.`RCUGRUP_ID` AS `SRCUGRUP_ID`,
        `A`.`RGRUP_NM` AS `SRGRUP_NM`,
        `A`.`CUGRUP_ID` AS `SCUGRUP_ID`,
        `A`.`REF_USER_GRUP_ID` AS `SREF_USER_GRUP_ID`,
        `A`.`GRUP_NM` AS `SGRUP_NM`,
        `A`.`CLUD_ID` AS `SCLUD_ID`,
        `A`.`LVL` AS `LVL`
from `TR_CLUD_USER_GRUP` `A`;