; controller/supervisord.conf
[supervisord]
nodaemon=true
logfile=/opt/connect/logs/supervisord.log
pidfile=/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=10

[program:web]
command=/usr/bin/java -server -Xms512m -Xmx1024m -Dfile.encoding=UTF-8 % (ENV_JAVA_TOOL_OPTIONS)s -jar /opt/connect/controller/web/controller-web-1.0.war
directory=/opt/connect/controller
autorestart=true
priority=20

[program:api]
command=/usr/bin/java -server -Xms512m -Xmx1024m -Dfile.encoding=UTF-8 % (ENV_JAVA_TOOL_OPTIONS)s -jar /opt/connect/controller/api/controller-api-1.0.jar
directory=/opt/connect/controller
autorestart=true
priority=20

[program:rpc]
command=/usr/bin/java -server -Xms2048m -Xmx3072m -Dpgct=connect-controller -Dpgct.home=/opt/connect/controller -Dfile.encoding=UTF-8 % (ENV_JAVA_TOOL_OPTIONS)s -jar /opt/connect/controller/rpc/controller-rpc-1.0.jar
directory=/opt/connect/controller
autorestart=true
priority=30

[program:check]
command=/usr/bin/java % (ENV_JAVA_TOOL_OPTIONS)s -jar /opt/connect/controller/check/controller-check-1.0.jar
directory=/opt/connect/controller
autorestart=true
priority=40
